i=$((i+1));var[$i]="%";brf[$i]="%"
i=$((i+1));var[$i]="10^9m^2\/yr";brf[$i]="10^9m^2\/yr"
i=$((i+1));var[$i]="1000s";brf[$i]="1000s"
i=$((i+1));var[$i]="4(KP)";brf[$i]=""
i=$((i+1));var[$i]="Abandoned Underground Mines";brf[$i]=""
i=$((i+1));var[$i]="Aboveground biomass";brf[$i]=""
i=$((i+1));var[$i]="Acrylonitrile";brf[$i]=""
i=$((i+1));var[$i]="Activity A.1";brf[$i]=""
i=$((i+1));var[$i]="Activity A.2";brf[$i]=""
i=$((i+1));var[$i]="Activity B.1";brf[$i]=""
i=$((i+1));var[$i]="Activity data";brf[$i]="AD"
i=$((i+1));var[$i]="Activity Data";brf[$i]="AD"
i=$((i+1));var[$i]="Activity";brf[$i]="ACT"
i=$((i+1));var[$i]="Additional Information (for Tier 2)";brf[$i]="INFOT2"
i=$((i+1));var[$i]="Additional Information for NIR-1";brf[$i]="INFONIR1"
i=$((i+1));var[$i]="Additional Information";brf[$i]="INFOADD"
i=$((i+1));var[$i]="Adipic Acid Production";brf[$i]=""
i=$((i+1));var[$i]="Aerosols";brf[$i]=""
i=$((i+1));var[$i]="Afforestation and Reforestation";brf[$i]=""
i=$((i+1));var[$i]="Aggregate F-gases";brf[$i]=""
i=$((i+1));var[$i]="Aggregate GHGs";brf[$i]="GHGs"
i=$((i+1));var[$i]="Agricultural Soils";brf[$i]="4D"
i=$((i+1));var[$i]="Agriculture";brf[$i]="3"
i=$((i+1));var[$i]="Agriculture\/Forestry\/Fishing";brf[$i]=""
i=$((i+1));var[$i]="Allocation by climate region";brf[$i]="ALLOCCLIMA"
i=$((i+1));var[$i]="Aluminium Production";brf[$i]=""
i=$((i+1));var[$i]="Ammonia Production";brf[$i]=""
i=$((i+1));var[$i]="Amount applied";brf[$i]="APPLIED"
i=$((i+1));var[$i]="Amount captured";brf[$i]=""
i=$((i+1));var[$i]="Amount of CH4 flared";brf[$i]=""
i=$((i+1));var[$i]="Amount of CH4 for energy recovery";brf[$i]="CHEENERGY"
i=$((i+1));var[$i]="Amount of fuel produced";brf[$i]="FUEL"
i=$((i+1));var[$i]="Amount of wastes incinerated\/open burned";brf[$i]=""
i=$((i+1));var[$i]="Amount";brf[$i]="AMOUNT"
i=$((i+1));var[$i]="Anaerobic Digestion at Biogas Facilities";brf[$i]=""
i=$((i+1));var[$i]="Anaerobic lagoon";brf[$i]=""
i=$((i+1));var[$i]="Anaerobic";brf[$i]=""
i=$((i+1));var[$i]="Animal Manure Applied to Soils";brf[$i]="MANFERT"
i=$((i+1));var[$i]="Annual change in stock";brf[$i]="STOCKCHANGE"
i=$((i+1));var[$i]="Annual Change in Total Long-term C Storage in HWP Waste";brf[$i]=""
i=$((i+1));var[$i]="Annual Change in Total Long-term C Storage";brf[$i]=""
i=$((i+1));var[$i]="Annual waste amount treated";brf[$i]=""
i=$((i+1));var[$i]="Annual waste at the SWDS";brf[$i]=""
i=$((i+1));var[$i]="Anthracite";brf[$i]=""
i=$((i+1));var[$i]="Apparent consumption";brf[$i]=""
i=$((i+1));var[$i]="Apparent energy consumption  (excluding non-energy use reductants and feedstocks)";brf[$i]=""
i=$((i+1));var[$i]="Approach B";brf[$i]=""
i=$((i+1));var[$i]="Approach B2";brf[$i]=""
i=$((i+1));var[$i]="Area burned";brf[$i]="AREA"
i=$((i+1));var[$i]="Area of cultivated organic soils";brf[$i]="AREA"
i=$((i+1));var[$i]="Area of mineral soil";brf[$i]="AREA"
i=$((i+1));var[$i]="Area of organic soil";brf[$i]="AREA"
i=$((i+1));var[$i]="Area subject to natural disturbances in the inventory year";brf[$i]="AREA"
i=$((i+1));var[$i]="Area subject to natural disturbances in the year when it was first reported";brf[$i]="AREA"
i=$((i+1));var[$i]="Area subject to the activity";brf[$i]="AREA"
i=$((i+1));var[$i]="Area";brf[$i]="AREA"
i=$((i+1));var[$i]="Article 3.3 Activities";brf[$i]=""
i=$((i+1));var[$i]="Article 3.4 Activities";brf[$i]=""
i=$((i+1));var[$i]="Atmospheric Deposition";brf[$i]="ATMD"
i=$((i+1));var[$i]="Atmospheric deposition";brf[$i]="ATMDEP"
i=$((i+1));var[$i]="Average CH4 conversion rate";brf[$i]="YM"
i=$((i+1));var[$i]="Average gross energy intake";brf[$i]="GE"
i=$((i+1));var[$i]="Aviation Gasoline";brf[$i]=""
i=$((i+1));var[$i]="Background level";brf[$i]=""
i=$((i+1));var[$i]="Barley";brf[$i]=""
i=$((i+1));var[$i]="Belowground biomass";brf[$i]=""
i=$((i+1));var[$i]="Biogenic";brf[$i]=""
i=$((i+1));var[$i]="Biological Treatment of Solid Waste";brf[$i]=""
i=$((i+1));var[$i]="Biomass available";brf[$i]=""
i=$((i+1));var[$i]="Biomass Burning";brf[$i]=""
i=$((i+1));var[$i]="Biomass";brf[$i]=""
i=$((i+1));var[$i]="Bitumen";brf[$i]=""
i=$((i+1));var[$i]="BKB and Patent Fuel";brf[$i]=""
i=$((i+1));var[$i]="Bruto Emissions";brf[$i]=""
i=$((i+1));var[$i]="Burned for fuel or as waste";brf[$i]=""
i=$((i+1));var[$i]="Business-as-usual projection";brf[$i]=""
i=$((i+1));var[$i]="By-Product Emissions";brf[$i]=""
i=$((i+1));var[$i]="By-Product Production";brf[$i]=""
i=$((i+1));var[$i]="C";brf[$i]="C"
i=$((i+1));var[$i]="C10F18";brf[$i]="C10F18"
i=$((i+1));var[$i]="C2F6";brf[$i]="C2F6"
i=$((i+1));var[$i]="C3F8";brf[$i]="C3F8"
i=$((i+1));var[$i]="C4F10";brf[$i]="C4F10"
i=$((i+1));var[$i]="C5F12";brf[$i]="C5F12"
i=$((i+1));var[$i]="C6F14";brf[$i]="C6F14"
i=$((i+1));var[$i]="Calcium Carbide";brf[$i]=""
i=$((i+1));var[$i]="Calorific value";brf[$i]=""
i=$((i+1));var[$i]="Caprolactam Glyoxal and Glyoxylic Acid Production";brf[$i]=""
i=$((i+1));var[$i]="Caprolactam";brf[$i]=""
i=$((i+1));var[$i]="Carbide Production";brf[$i]=""
i=$((i+1));var[$i]="Carbon Black";brf[$i]=""
i=$((i+1));var[$i]="Carbon content";brf[$i]="C"
i=$((i+1));var[$i]="Carbon stock change in above-ground biomass per area";brf[$i]=""
i=$((i+1));var[$i]="Carbon stock change in above-ground biomass";brf[$i]=""
i=$((i+1));var[$i]="Carbon stock change in below-ground biomass per area";brf[$i]=""
i=$((i+1));var[$i]="Carbon stock change in below-ground biomass";brf[$i]=""
i=$((i+1));var[$i]="Carbon stock change in living biomass";brf[$i]=""
i=$((i+1));var[$i]="Carbon stock change";brf[$i]=""
i=$((i+1));var[$i]="Carbon stock changes";brf[$i]="DELTAC"
i=$((i+1));var[$i]="Carbon stored";brf[$i]=""
i=$((i+1));var[$i]="Cars";brf[$i]=""
i=$((i+1));var[$i]="Cattle";brf[$i]="CATT"
i=$((i+1));var[$i]="c-C3F6";brf[$i]=""
i=$((i+1));var[$i]="cC3F6";brf[$i]="cC3F6"
i=$((i+1));var[$i]="c-C4F8";brf[$i]=""
i=$((i+1));var[$i]="cC4F8";brf[$i]="cC4F8"
i=$((i+1));var[$i]="Cement Production";brf[$i]=""
i=$((i+1));var[$i]="Ceramics";brf[$i]=""
i=$((i+1));var[$i]="Cereals";brf[$i]="CERE"
i=$((i+1));var[$i]="CF4";brf[$i]="CF4"
i=$((i+1));var[$i]="CH4 and N2O emissions from drained and rewetted organic soils";brf[$i]="HISTDRW"
i=$((i+1));var[$i]="CH4 Emissions";brf[$i]="CH4EM"
i=$((i+1));var[$i]="CH4 per area";brf[$i]="CH4"
i=$((i+1));var[$i]="CH4 producing potential (average)";brf[$i]="B0"
i=$((i+1));var[$i]="CH4";brf[$i]="CH4"
i=$((i+1));var[$i]="Change in carbon pool reported";brf[$i]=""
i=$((i+1));var[$i]="Change in carbon stock";brf[$i]="DELTAC"
i=$((i+1));var[$i]="Chemical Industry";brf[$i]=""
i=$((i+1));var[$i]="Chemicals";brf[$i]=""
i=$((i+1));var[$i]="Classification Root";brf[$i]=""
i=$((i+1));var[$i]="Closed Cells";brf[$i]=""
i=$((i+1));var[$i]="CO";brf[$i]="CO"
i=$((i+1));var[$i]="CO2 Emissions";brf[$i]="CO2EM"
i=$((i+1));var[$i]="CO2 per area";brf[$i]=""
i=$((i+1));var[$i]="CO2 Transport and Storage";brf[$i]=""
i=$((i+1));var[$i]="CO2 transported or injected";brf[$i]=""
i=$((i+1));var[$i]="CO2";brf[$i]="CO2"
i=$((i+1));var[$i]="Coal Mining and Handling";brf[$i]=""
i=$((i+1));var[$i]="Coal Tar";brf[$i]=""
i=$((i+1));var[$i]="Coke Oven\/Gas Coke";brf[$i]=""
i=$((i+1));var[$i]="Coking Coal";brf[$i]=""
i=$((i+1));var[$i]="Combined";brf[$i]=""
i=$((i+1));var[$i]="Combustion factor";brf[$i]=""
i=$((i+1));var[$i]="Commercial Refrigeration";brf[$i]=""
i=$((i+1));var[$i]="Commercial\/Institutional";brf[$i]=""
i=$((i+1));var[$i]="Comparison of CO2 Emissions from Fuel Combustion";brf[$i]=""
i=$((i+1));var[$i]="Composting";brf[$i]=""
i=$((i+1));var[$i]="Contained";brf[$i]=""
i=$((i+1));var[$i]="Continuously Flooded";brf[$i]="3C1a"
i=$((i+1));var[$i]="Controlled Burning";brf[$i]=""
i=$((i+1));var[$i]="Conversion factor";brf[$i]=""
i=$((i+1));var[$i]="Converted to Cropland";brf[$i]=""
i=$((i+1));var[$i]="Converted to Forest land (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Converted to Forest land";brf[$i]=""
i=$((i+1));var[$i]="Converted to Grassland (managed)";brf[$i]=""
i=$((i+1));var[$i]="Converted to Grassland (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Converted to Grassland";brf[$i]=""
i=$((i+1));var[$i]="Converted to Other land";brf[$i]=""
i=$((i+1));var[$i]="Converted to Settlements";brf[$i]=""
i=$((i+1));var[$i]="Converted to Total unmanaged land";brf[$i]=""
i=$((i+1));var[$i]="Converted to Wetlands (managed)";brf[$i]=""
i=$((i+1));var[$i]="Converted to Wetlands (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Converted to Wetlands";brf[$i]=""
i=$((i+1));var[$i]="Cool";brf[$i]="COOL"
i=$((i+1));var[$i]="Crop  production";brf[$i]="PROD"
i=$((i+1));var[$i]="Crop Residues";brf[$i]="CRES"
i=$((i+1));var[$i]="Cropland (managed)";brf[$i]=""
i=$((i+1));var[$i]="Cropland Management";brf[$i]=""
i=$((i+1));var[$i]="Cropland";brf[$i]=""
i=$((i+1));var[$i]="Cropland";brf[$i]="CROPL"
i=$((i+1));var[$i]="Crude Oil";brf[$i]=""
i=$((i+1));var[$i]="Cultivation of Organic Soils";brf[$i]="HIST"
i=$((i+1));var[$i]="Daily spread";brf[$i]=""
i=$((i+1));var[$i]="Dairy CATT";brf[$i]="DAIR"
i=$((i+1));var[$i]="Deadwood";brf[$i]=""
i=$((i+1));var[$i]="Deep Water";brf[$i]="3C3"
i=$((i+1));var[$i]="Deforestation";brf[$i]=""
i=$((i+1));var[$i]="Deforested land previously reported under afforestation\/reforestation and forest management  and subject to natural disturbances";brf[$i]=""
i=$((i+1));var[$i]="Degree of utilization of modern centralized WWT plants";brf[$i]=""
i=$((i+1));var[$i]="Diesel Oil";brf[$i]=""
i=$((i+1));var[$i]="Difference";brf[$i]="DIFF"
i=$((i+1));var[$i]="Digesters";brf[$i]=""
i=$((i+1));var[$i]="Digestibility of feed";brf[$i]="DIGEST"
i=$((i+1));var[$i]="Direct and indirect N2O emissions from N fertilization";brf[$i]="NFERT"
i=$((i+1));var[$i]="Direct emissions per MMS";brf[$i]="EM"
i=$((i+1));var[$i]="Direct N2O Emissions From Managed Soils";brf[$i]="SOILS"
i=$((i+1));var[$i]="Direct N2O Emissions from N inputs";brf[$i]="NINPUTS"
i=$((i+1));var[$i]="Direct N2O Emissions from N Mineralization\/Immobilization";brf[$i]="MINER"
i=$((i+1));var[$i]="Direct Reduced Iron";brf[$i]=""
i=$((i+1));var[$i]="Distribution of Oil Products";brf[$i]=""
i=$((i+1));var[$i]="Distribution";brf[$i]=""
i=$((i+1));var[$i]="DOC";brf[$i]="DOC"
i=$((i+1));var[$i]="Documentation box";brf[$i]=""
i=$((i+1));var[$i]="Dolomite CaMg(CO3)2";brf[$i]=""
i=$((i+1));var[$i]="Domestic Aviation";brf[$i]=""
i=$((i+1));var[$i]="Domestic Navigation";brf[$i]=""
i=$((i+1));var[$i]="Domestic Refrigeration";brf[$i]=""
i=$((i+1));var[$i]="Domestic Wastewater";brf[$i]=""
i=$((i+1));var[$i]="Domestic";brf[$i]=""
i=$((i+1));var[$i]="Drained Organic Soils";brf[$i]=""
i=$((i+1));var[$i]="Drained Organic Soils";brf[$i]="HISTD"
i=$((i+1));var[$i]="Drained rewetted and other soils";brf[$i]=""
i=$((i+1));var[$i]="Drought Prone";brf[$i]="3C2b"
i=$((i+1));var[$i]="Dry matter (dm) fraction of residue";brf[$i]=""
i=$((i+1));var[$i]="Electrical Equipment";brf[$i]=""
i=$((i+1));var[$i]="Electronics Industry";brf[$i]=""
i=$((i+1));var[$i]="Emission factor information";brf[$i]="INFOEF"
i=$((i+1));var[$i]="Emission factor";brf[$i]="EF"
i=$((i+1));var[$i]="Emissions and removals from drainage and rewetting and other management of organic and mineral soils";brf[$i]="SOILSDRW"
i=$((i+1));var[$i]="Emissions and removals from natural disturbances";brf[$i]="NATDIST"
i=$((i+1));var[$i]="Emissions from areas subject to natural disturbances";brf[$i]="NATDIST"
i=$((i+1));var[$i]="Emissions from natural disturbances";brf[$i]=""
i=$((i+1));var[$i]="Emissions in inventory year that can be excludin in the inventory year";brf[$i]=""
i=$((i+1));var[$i]="Emissions";brf[$i]="EM"
i=$((i+1));var[$i]="Emissive";brf[$i]=""
i=$((i+1));var[$i]="Energy consumption difference";brf[$i]=""
i=$((i+1));var[$i]="Energy Industries";brf[$i]=""
i=$((i+1));var[$i]="Energy";brf[$i]=""
i=$((i+1));var[$i]="Enteric Fermentation";brf[$i]="3A"
i=$((i+1));var[$i]="Ethane";brf[$i]=""
i=$((i+1));var[$i]="Ethylene Dichloride and Vinyl Chloride Monomer";brf[$i]=""
i=$((i+1));var[$i]="Ethylene Oxide";brf[$i]=""
i=$((i+1));var[$i]="Ethylene";brf[$i]=""
i=$((i+1));var[$i]="Excluded from reference approach";brf[$i]=""
i=$((i+1));var[$i]="Exploration";brf[$i]=""
i=$((i+1));var[$i]="Exports";brf[$i]=""
i=$((i+1));var[$i]="Factors used to convert from product units to carbon";brf[$i]=""
i=$((i+1));var[$i]="Farming";brf[$i]="FARM"
i=$((i+1));var[$i]="Feeding situation";brf[$i]="FEEDING"
i=$((i+1));var[$i]="Feedstocks reductants and other non-energy use of fuels";brf[$i]=""
i=$((i+1));var[$i]="Ferroalloys Production";brf[$i]=""
i=$((i+1));var[$i]="Fertilization";brf[$i]="FERT"
i=$((i+1));var[$i]="F-gases used in foundries";brf[$i]=""
i=$((i+1));var[$i]="Fgases";brf[$i]="Fgases"
i=$((i+1));var[$i]="Field Burning of Agricultural Residues";brf[$i]="3F"
i=$((i+1));var[$i]="Final area (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Final area";brf[$i]=""
i=$((i+1));var[$i]="Fire Protection";brf[$i]=""
i=$((i+1));var[$i]="Fishing";brf[$i]="FISH"
i=$((i+1));var[$i]="Flaring";brf[$i]=""
i=$((i+1));var[$i]="Flood Prone";brf[$i]="3C2a"
i=$((i+1));var[$i]="Flooded Land";brf[$i]="FLODL"
i=$((i+1));var[$i]="Fluorochemical Production";brf[$i]=""
i=$((i+1));var[$i]="Foam Blowing Agents";brf[$i]=""
i=$((i+1));var[$i]="Food Processing Beverages and Tobacco";brf[$i]=""
i=$((i+1));var[$i]="For domestic storage";brf[$i]=""
i=$((i+1));var[$i]="For storage in other countries";brf[$i]=""
i=$((i+1));var[$i]="Forest land (managed)";brf[$i]=""
i=$((i+1));var[$i]="Forest land (specify ecological zone)";brf[$i]=""
i=$((i+1));var[$i]="Forest land (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Forest Land";brf[$i]=""
i=$((i+1));var[$i]="Forest Land";brf[$i]="FOREL"
i=$((i+1));var[$i]="Forest management reference level and technical correction";brf[$i]=""
i=$((i+1));var[$i]="Forest Management";brf[$i]=""
i=$((i+1));var[$i]="Fossil fuels";brf[$i]=""
i=$((i+1));var[$i]="Fraction burned in fields";brf[$i]=""
i=$((i+1));var[$i]="Fraction excluded from reference approach";brf[$i]=""
i=$((i+1));var[$i]="Fraction of carbon oxidized";brf[$i]=""
i=$((i+1));var[$i]="Fraction of industrial and commercial co-discharged protein into the sewer system";brf[$i]=""
i=$((i+1));var[$i]="Fraction of nitrogen in protein";brf[$i]="NINPROT"
i=$((i+1));var[$i]="Fraction of non-consumed protein added to the wastewater";brf[$i]=""
i=$((i+1));var[$i]="Fraction oxidized";brf[$i]=""
i=$((i+1));var[$i]="Fuel Combustion - Reference Approach";brf[$i]=""
i=$((i+1));var[$i]="Fuel Combustion - Sectoral approach";brf[$i]=""
i=$((i+1));var[$i]="Fuel Consumption Distribution";brf[$i]=""
i=$((i+1));var[$i]="Fuel Consumption";brf[$i]=""
i=$((i+1));var[$i]="Fuel quantity";brf[$i]=""
i=$((i+1));var[$i]="Fuels";brf[$i]=""
i=$((i+1));var[$i]="Fugitive Emissions from Fuels";brf[$i]=""
i=$((i+1));var[$i]="Fugitive Emissions";brf[$i]=""
i=$((i+1));var[$i]="g\/kg";brf[$i]="g\/kg"
i=$((i+1));var[$i]="g\/m^2";brf[$i]="g\/m^2"
i=$((i+1));var[$i]="Gains";brf[$i]=""
i=$((i+1));var[$i]="Gas Biomass";brf[$i]=""
i=$((i+1));var[$i]="Gas";brf[$i]="GAS"
i=$((i+1));var[$i]="Gas\/Diesel Oil";brf[$i]=""
i=$((i+1));var[$i]="Gaseous Fuels";brf[$i]=""
i=$((i+1));var[$i]="Gasoline";brf[$i]=""
i=$((i+1));var[$i]="Geographic location";brf[$i]="GEOLOC"
i=$((i+1));var[$i]="GHGs";brf[$i]="GHGs"
i=$((i+1));var[$i]="Glass production";brf[$i]=""
i=$((i+1));var[$i]="Glyoxal";brf[$i]=""
i=$((i+1));var[$i]="Glyoxylic Acid";brf[$i]=""
i=$((i+1));var[$i]="Grassland (managed)";brf[$i]=""
i=$((i+1));var[$i]="Grassland (specify ecological zone)";brf[$i]=""
i=$((i+1));var[$i]="Grassland (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Grassland";brf[$i]=""
i=$((i+1));var[$i]="Grassland";brf[$i]="GRASL"
i=$((i+1));var[$i]="GrassLand";brf[$i]="GRASL"
i=$((i+1));var[$i]="Grazing Land Management";brf[$i]=""
i=$((i+1));var[$i]="Greenhouse gas sources reported";brf[$i]="SOURCE"
i=$((i+1));var[$i]="Gross energy";brf[$i]="GROSSENER"
i=$((i+1));var[$i]="h\/day";brf[$i]="h\/day"
i=$((i+1));var[$i]="ha";brf[$i]="ha"
i=$((i+1));var[$i]="ha\/yr";brf[$i]="ha\/yr"
i=$((i+1));var[$i]="Half-life";brf[$i]="HALFLIFE"
i=$((i+1));var[$i]="Harvested and converted forest plantations";brf[$i]=""
i=$((i+1));var[$i]="Harvested area for Upland Rice";brf[$i]="AREA"
i=$((i+1));var[$i]="Harvested area";brf[$i]="AREA"
i=$((i+1));var[$i]="Harvested Wood Products";brf[$i]=""
i=$((i+1));var[$i]="Heat Transfer Fluid";brf[$i]=""
i=$((i+1));var[$i]="Heavy duty trucks and buses";brf[$i]=""
i=$((i+1));var[$i]="HFC-125";brf[$i]=""
i=$((i+1));var[$i]="HFC125";brf[$i]="HFC125"
i=$((i+1));var[$i]="HFC-134";brf[$i]=""
i=$((i+1));var[$i]="HFC134";brf[$i]="HFC134"
i=$((i+1));var[$i]="HFC-134a";brf[$i]=""
i=$((i+1));var[$i]="HFC134a";brf[$i]="HFC134a"
i=$((i+1));var[$i]="HFC-143";brf[$i]=""
i=$((i+1));var[$i]="HFC143";brf[$i]="HFC143"
i=$((i+1));var[$i]="HFC-143a";brf[$i]=""
i=$((i+1));var[$i]="HFC143a";brf[$i]="HFC143a"
i=$((i+1));var[$i]="HFC-152";brf[$i]=""
i=$((i+1));var[$i]="HFC152";brf[$i]="HFC152"
i=$((i+1));var[$i]="HFC-152a";brf[$i]=""
i=$((i+1));var[$i]="HFC152a";brf[$i]="HFC152a"
i=$((i+1));var[$i]="HFC-161";brf[$i]=""
i=$((i+1));var[$i]="HFC161";brf[$i]="HFC161"
i=$((i+1));var[$i]="HFC-227ea";brf[$i]=""
i=$((i+1));var[$i]="HFC227ea";brf[$i]="HFC227ea"
i=$((i+1));var[$i]="HFC-23";brf[$i]=""
i=$((i+1));var[$i]="HFC23";brf[$i]="HFC23"
i=$((i+1));var[$i]="HFC-236cb";brf[$i]=""
i=$((i+1));var[$i]="HFC236cb";brf[$i]="HFC236cb"
i=$((i+1));var[$i]="HFC-236ea";brf[$i]=""
i=$((i+1));var[$i]="HFC236ea";brf[$i]="HFC236ea"
i=$((i+1));var[$i]="HFC-236fa";brf[$i]=""
i=$((i+1));var[$i]="HFC236fa";brf[$i]="HFC236fa"
i=$((i+1));var[$i]="HFC-245ca";brf[$i]=""
i=$((i+1));var[$i]="HFC245ca";brf[$i]="HFC245ca"
i=$((i+1));var[$i]="HFC-245fa";brf[$i]=""
i=$((i+1));var[$i]="HFC245fa";brf[$i]="HFC245fa"
i=$((i+1));var[$i]="HFC-32";brf[$i]=""
i=$((i+1));var[$i]="HFC32";brf[$i]="HFC32"
i=$((i+1));var[$i]="HFC-365mfc";brf[$i]=""
i=$((i+1));var[$i]="HFC365mfc";brf[$i]="HFC365mfc"
i=$((i+1));var[$i]="HFC-41";brf[$i]=""
i=$((i+1));var[$i]="HFC41";brf[$i]="HFC41"
i=$((i+1));var[$i]="HFC-43-10mee";brf[$i]=""
i=$((i+1));var[$i]="HFC4310mee";brf[$i]="HFC4310mee"
i=$((i+1));var[$i]="HFCs and PFCs";brf[$i]=""
i=$((i+1));var[$i]="HFCs";brf[$i]="HFCs"
i=$((i+1));var[$i]="HFCs_PFCs";brf[$i]="HFCs_PFCs"
i=$((i+1));var[$i]="HWP from domestic harvest";brf[$i]="HWPD"
i=$((i+1));var[$i]="HWP in solid waste disposal sites produced from domestic harvest";brf[$i]=""
i=$((i+1));var[$i]="HWP in SWDS";brf[$i]=""
i=$((i+1));var[$i]="HWP in SWDS";brf[$i]="HWPS"
i=$((i+1));var[$i]="HWP in use from domestic consumption";brf[$i]=""
i=$((i+1));var[$i]="HWP in use from domestic harvest";brf[$i]=""
i=$((i+1));var[$i]="HWP in use";brf[$i]="HWPU"
i=$((i+1));var[$i]="HWP Produced and Consumed Domestically";brf[$i]=""
i=$((i+1));var[$i]="HWP Produced and Exported";brf[$i]=""
i=$((i+1));var[$i]="HWP";brf[$i]=""
i=$((i+1));var[$i]="Implied carbon stock change factors";brf[$i]=""
i=$((i+1));var[$i]="Implied emission factor";brf[$i]="IEF"
i=$((i+1));var[$i]="Implied emission factors";brf[$i]="IEF"
i=$((i+1));var[$i]="Imports";brf[$i]=""
i=$((i+1));var[$i]="Incineration and Open Burning of Waste";brf[$i]=""
i=$((i+1));var[$i]="Indirect emissions";brf[$i]="EMIND"
i=$((i+1));var[$i]="Indirect N2O Emissions From Managed Soils";brf[$i]="N2OIND"
i=$((i+1));var[$i]="Indirect N2O Emissions";brf[$i]=""
i=$((i+1));var[$i]="Industrial Processes and Product Use";brf[$i]=""
i=$((i+1));var[$i]="Industrial Refrigeration";brf[$i]=""
i=$((i+1));var[$i]="Industrial Wastewater";brf[$i]=""
i=$((i+1));var[$i]="Information item";brf[$i]=""
i=$((i+1));var[$i]="Information Items on deforestation wildfires";brf[$i]=""
i=$((i+1));var[$i]="Initial area (unmanaged)";brf[$i]="AREA"
i=$((i+1));var[$i]="Initial area";brf[$i]="AREA"
i=$((i+1));var[$i]="Injection and Storage";brf[$i]=""
i=$((i+1));var[$i]="Injection";brf[$i]=""
i=$((i+1));var[$i]="Inorganic N Fertilizers";brf[$i]="INORGFERT"
i=$((i+1));var[$i]="Inorganic N Fertilizers";brf[$i]="MINFERT"
i=$((i+1));var[$i]="Integrated Circuit or Semiconductor";brf[$i]=""
i=$((i+1));var[$i]="Intermittently Flooded";brf[$i]="3C1b"
i=$((i+1));var[$i]="International Aviation";brf[$i]=""
i=$((i+1));var[$i]="International bunkers";brf[$i]=""
i=$((i+1));var[$i]="International Bunkers";brf[$i]=""
i=$((i+1));var[$i]="International Navigation";brf[$i]=""
i=$((i+1));var[$i]="International";brf[$i]=""
i=$((i+1));var[$i]="Iron and Steel Production";brf[$i]=""
i=$((i+1));var[$i]="Iron and Steel";brf[$i]=""
i=$((i+1));var[$i]="Irrigated";brf[$i]="3C1"
i=$((i+1));var[$i]="Jet Kerosene";brf[$i]=""
i=$((i+1));var[$i]="kg CH4\/ha";brf[$i]="kgCH4\/ha"
i=$((i+1));var[$i]="kg CO2\/ha";brf[$i]="kgCO2\/ha"
i=$((i+1));var[$i]="kg dm\/head\/day";brf[$i]="kgdm\/head\/day"
i=$((i+1));var[$i]="kg N\/yr";brf[$i]="kgN\/yr"
i=$((i+1));var[$i]="kg N2O\/kg N handled";brf[$i]="kgN2O\/kgN handled"
i=$((i+1));var[$i]="kg N2O\/kg N";brf[$i]="kgN2O\/kgN"
i=$((i+1));var[$i]="kg N2O-N\/ha";brf[$i]="kgN2O-N\/ha"
i=$((i+1));var[$i]="kg N2O-N\/kg N";brf[$i]="kgN2O-N\/kgN"
i=$((i+1));var[$i]="kg";brf[$i]="kg"
i=$((i+1));var[$i]="kg\/day";brf[$i]="kg\/day"
i=$((i+1));var[$i]="kg\/head\/yr";brf[$i]="kg\/head\/yr"
i=$((i+1));var[$i]="kg\/kg DC";brf[$i]="kg\/kgDC"
i=$((i+1));var[$i]="kg\/kt";brf[$i]="kg\/kt"
i=$((i+1));var[$i]="kg\/person\/yr";brf[$i]="kg\/person\/yr"
i=$((i+1));var[$i]="kg\/t dm";brf[$i]="kg\/t dm"
i=$((i+1));var[$i]="kg\/t";brf[$i]="kg\/t"
i=$((i+1));var[$i]="kg\/TJ";brf[$i]="kg\/TJ"
i=$((i+1));var[$i]="kg\/unit";brf[$i]="kg\/unit"
i=$((i+1));var[$i]="kg\/yr";brf[$i]="kg\/yr"
i=$((i+1));var[$i]="kha";brf[$i]="kha"
i=$((i+1));var[$i]="kha\/yr";brf[$i]="kha\/yr"
i=$((i+1));var[$i]="kt C";brf[$i]="ktC"
i=$((i+1));var[$i]="kt CO2 equivalent";brf[$i]="ktCO2eq"
i=$((i+1));var[$i]="kt CO2 equivalent\/yr";brf[$i]="ktCO2eq\/yr"
i=$((i+1));var[$i]="kt DC";brf[$i]="ktDC"
i=$((i+1));var[$i]="kt dm";brf[$i]="ktdm"
i=$((i+1));var[$i]="kt N\/yr";brf[$i]="ktN\/yr"
i=$((i+1));var[$i]="kt";brf[$i]="kt"
i=$((i+1));var[$i]="Land area";brf[$i]="AREA"
i=$((i+1));var[$i]="Land otherwise subject to forest management or elected activities under Article 3.4";brf[$i]=""
i=$((i+1));var[$i]="Land subject to natural disturbances";brf[$i]=""
i=$((i+1));var[$i]="Land Transition Matrix";brf[$i]=""
i=$((i+1));var[$i]="Land Use Land-Use Change and Forestry";brf[$i]=""
i=$((i+1));var[$i]="Land Use";brf[$i]=""
i=$((i+1));var[$i]="Land";brf[$i]="LAND"
i=$((i+1));var[$i]="Lead Production";brf[$i]=""
i=$((i+1));var[$i]="Light duty trucks";brf[$i]=""
i=$((i+1));var[$i]="Lignite";brf[$i]=""
i=$((i+1));var[$i]="Lime Production";brf[$i]=""
i=$((i+1));var[$i]="Limestone CaCO3";brf[$i]=""
i=$((i+1));var[$i]="Liming";brf[$i]="3G"
i=$((i+1));var[$i]="Liquefied Petroleum Gases (LPG)";brf[$i]=""
i=$((i+1));var[$i]="Liquid Biomass";brf[$i]=""
i=$((i+1));var[$i]="Liquid Fuels";brf[$i]=""
i=$((i+1));var[$i]="Liquid system";brf[$i]="LIQU"
i=$((i+1));var[$i]="Litter";brf[$i]=""
i=$((i+1));var[$i]="Livestock";brf[$i]=""
i=$((i+1));var[$i]="Long-term Storage of C in Waste Disposal Sites";brf[$i]=""
i=$((i+1));var[$i]="Losses";brf[$i]=""
i=$((i+1));var[$i]="Lubricant Use";brf[$i]=""
i=$((i+1));var[$i]="Lubricants";brf[$i]=""
i=$((i+1));var[$i]="m^3";brf[$i]="m^3"
i=$((i+1));var[$i]="m^3\/kg VS";brf[$i]="m^3\/kgVS"
i=$((i+1));var[$i]="Magnesium Production";brf[$i]=""
i=$((i+1));var[$i]="Maize";brf[$i]="MAIZ"
i=$((i+1));var[$i]="Managed Waste Disposal Sites";brf[$i]=""
i=$((i+1));var[$i]="managed";brf[$i]=""
i=$((i+1));var[$i]="Manufacture of Solid Fuels and Other Energy Industries";brf[$i]=""
i=$((i+1));var[$i]="Manufacturing Industries and Construction";brf[$i]=""
i=$((i+1));var[$i]="Manure Management";brf[$i]="3B"
i=$((i+1));var[$i]="Margin";brf[$i]=""
i=$((i+1));var[$i]="MCF";brf[$i]="MCF"
i=$((i+1));var[$i]="Medical Applications";brf[$i]=""
i=$((i+1));var[$i]="Memo Item";brf[$i]=""
i=$((i+1));var[$i]="Metal Industry";brf[$i]=""
i=$((i+1));var[$i]="Metered Dose Inhalers";brf[$i]=""
i=$((i+1));var[$i]="Methane conversion factor";brf[$i]="MCF"
i=$((i+1));var[$i]="Methanol";brf[$i]=""
i=$((i+1));var[$i]="Method";brf[$i]=""
i=$((i+1));var[$i]="metric t";brf[$i]="metric t"
i=$((i+1));var[$i]="Mg";brf[$i]="Mg"
i=$((i+1));var[$i]="Milk yield";brf[$i]="MILK"
i=$((i+1));var[$i]="Mineral Industry";brf[$i]=""
i=$((i+1));var[$i]="Mineral soils";brf[$i]="MINS"
i=$((i+1));var[$i]="Mineral soils";brf[$i]="MINSOILS"
i=$((i+1));var[$i]="Mineral";brf[$i]=""
i=$((i+1));var[$i]="Mineralization of Soil Organic Matter";brf[$i]="MINERSOM"
i=$((i+1));var[$i]="Minimum height (2-5 m)";brf[$i]=""
i=$((i+1));var[$i]="Minimum land area (0.05-1 ha)";brf[$i]=""
i=$((i+1));var[$i]="Minimum land cover (10-30 %)";brf[$i]=""
i=$((i+1));var[$i]="Mining Activities";brf[$i]=""
i=$((i+1));var[$i]="MixHFCs";brf[$i]="MixHFCs"
i=$((i+1));var[$i]="MixHFCs_PFCs";brf[$i]="MixHFCs_PFCs"
i=$((i+1));var[$i]="MixPFCs";brf[$i]="MixPFCs"
i=$((i+1));var[$i]="MJ\/day";brf[$i]="MJ\/day"
i=$((i+1));var[$i]="MJ\/head\/day";brf[$i]="MJ\/head\/day"
i=$((i+1));var[$i]="Mobile Air-Conditioning";brf[$i]=""
i=$((i+1));var[$i]="Mobile Combustion";brf[$i]="MCOMB"
i=$((i+1));var[$i]="Motorcycles";brf[$i]=""
i=$((i+1));var[$i]="Mt";brf[$i]="Mt"
i=$((i+1));var[$i]="Multilateral Operations";brf[$i]=""
i=$((i+1));var[$i]="Multiple aeration";brf[$i]="3C1b2"
i=$((i+1));var[$i]="Municipal Solid Waste";brf[$i]=""
i=$((i+1));var[$i]="N excretion on pasture range and paddock";brf[$i]="NEXC"
i=$((i+1));var[$i]="N from fertilizers and other agricultural inputs that is lost through leaching and run-off";brf[$i]="AD"
i=$((i+1));var[$i]="N from fertlizers and other that is lost through leaching and run-off from managed soils";brf[$i]="AD"
i=$((i+1));var[$i]="N in crop residues returned to soils";brf[$i]="AD"
i=$((i+1));var[$i]="N in effluent";brf[$i]="AD"
i=$((i+1));var[$i]="N in mineral soils that is mineralized in association with loss of soil C";brf[$i]="AD"
i=$((i+1));var[$i]="N input from application of inorganic fertilizers to cropland and grassland";brf[$i]="AD"
i=$((i+1));var[$i]="N input from application of other organic fertilizers";brf[$i]="AD"
i=$((i+1));var[$i]="N input from manure applied to soils";brf[$i]="AD"
i=$((i+1));var[$i]="N input from organic N fertilizers to cropland and grassland";brf[$i]="AD"
i=$((i+1));var[$i]="N input from sewage sludge applied to soils";brf[$i]="AD"
i=$((i+1));var[$i]="N lost through leaching and run-off";brf[$i]="NLOST"
i=$((i+1));var[$i]="N volatized from managed soils from inputs of N";brf[$i]="NVOLA"
i=$((i+1));var[$i]="N2O and NMVOC Emissions";brf[$i]=""
i=$((i+1));var[$i]="N2O emissions from N mineralization\/immobilization due to carbon loss\/gain associated with land-use conversions and management change in mineral soils";brf[$i]=""
i=$((i+1));var[$i]="N2O Emissions per MMS";brf[$i]="N2OEM"
i=$((i+1));var[$i]="N2O from Product Uses";brf[$i]=""
i=$((i+1));var[$i]="N2O";brf[$i]="N2O"
i=$((i+1));var[$i]="N2O-N emissions per unit of fertilizer";brf[$i]="N2OEFFERT"
i=$((i+1));var[$i]="N2O-N per area";brf[$i]="N2OEFAREA"
i=$((i+1));var[$i]="Naphtha";brf[$i]=""
i=$((i+1));var[$i]="Natural disturbances";brf[$i]="NATDIST"
i=$((i+1));var[$i]="Natural Gas (Dry)";brf[$i]=""
i=$((i+1));var[$i]="Natural Gas Liquids";brf[$i]=""
i=$((i+1));var[$i]="Natural Gas";brf[$i]=""
i=$((i+1));var[$i]="Net carbon emissions";brf[$i]=""
i=$((i+1));var[$i]="Net carbon stock change in dead organic matter per area";brf[$i]=""
i=$((i+1));var[$i]="Net carbon stock change in dead organic matter";brf[$i]=""
i=$((i+1));var[$i]="Net carbon stock change in dead wood per area";brf[$i]=""
i=$((i+1));var[$i]="Net carbon stock change in dead wood";brf[$i]=""
i=$((i+1));var[$i]="Net carbon stock change in litter per area";brf[$i]=""
i=$((i+1));var[$i]="Net carbon stock change in litter";brf[$i]=""
i=$((i+1));var[$i]="Net carbon stock change in soils per area";brf[$i]=""
i=$((i+1));var[$i]="Net carbon stock change in soils";brf[$i]=""
i=$((i+1));var[$i]="Net change";brf[$i]=""
i=$((i+1));var[$i]="Newly established forest";brf[$i]=""
i=$((i+1));var[$i]="NF3";brf[$i]="NF3"
i=$((i+1));var[$i]="NH3";brf[$i]="NH3"
i=$((i+1));var[$i]="NIR-1";brf[$i]="NIR1"
i=$((i+1));var[$i]="NIR-2";brf[$i]="NIR2"
i=$((i+1));var[$i]="NIR-2.1";brf[$i]="NIR2.1"
i=$((i+1));var[$i]="Nitric Acid Production";brf[$i]=""
i=$((i+1));var[$i]="Nitrogen excretion per MMS";brf[$i]="NEXC"
i=$((i+1));var[$i]="Nitrogen excretion rate";brf[$i]="NEXC"
i=$((i+1));var[$i]="Nitrogen leaching and run-off";brf[$i]="NLF"
i=$((i+1));var[$i]="Nitrogen Leaching and Run-off";brf[$i]="NLR"
i=$((i+1));var[$i]="Nitrogen mineralization in mineral soils";brf[$i]="NMINERSOIL"
i=$((i+1));var[$i]="NMVOC";brf[$i]="NMVOC"
i=$((i+1));var[$i]="no classification";brf[$i]=""
i=$((i+1));var[$i]="no gas";brf[$i]=""
i=$((i+1));var[$i]="no method";brf[$i]=""
i=$((i+1));var[$i]="no option";brf[$i]=""
i=$((i+1));var[$i]="no source";brf[$i]=""
i=$((i+1));var[$i]="no target";brf[$i]=""
i=$((i+1));var[$i]="no type";brf[$i]=""
i=$((i+1));var[$i]="NO";brf[$i]="NO"
i=$((i+1));var[$i]="Non-biogenic";brf[$i]=""
i=$((i+1));var[$i]="Non-DAIR";brf[$i]="NDAI"
i=$((i+1));var[$i]="Non-energy Products from Fuels and Solvent Use";brf[$i]=""
i=$((i+1));var[$i]="Non-Ferrous Metals";brf[$i]=""
i=$((i+1));var[$i]="Non-metallic minerals";brf[$i]=""
i=$((i+1));var[$i]="Non-metallurgical Magnesium Production";brf[$i]=""
i=$((i+1));var[$i]="NOx";brf[$i]="NOx"
i=$((i+1));var[$i]="Off-road vehicles and other machinery";brf[$i]="OFFROAD"
i=$((i+1));var[$i]="Oil and Natural Gas and Other Emissions from Energy Production";brf[$i]=""
i=$((i+1));var[$i]="Oil Shale and Tar Sand";brf[$i]=""
i=$((i+1));var[$i]="Oil";brf[$i]=""
i=$((i+1));var[$i]="Open Burning of Waste";brf[$i]=""
i=$((i+1));var[$i]="Open Cells";brf[$i]=""
i=$((i+1));var[$i]="Operation";brf[$i]=""
i=$((i+1));var[$i]="Option A";brf[$i]=""
i=$((i+1));var[$i]="Organic amendments added";brf[$i]=""
i=$((i+1));var[$i]="Organic N Fertilizers";brf[$i]="ORGFERT"
i=$((i+1));var[$i]="Organic soils";brf[$i]="HIST"
i=$((i+1));var[$i]="Organic soils";brf[$i]="ORGSOILS"
i=$((i+1));var[$i]="Organic";brf[$i]=""
i=$((i+1));var[$i]="Orimulsion";brf[$i]=""
i=$((i+1));var[$i]="Other activity";brf[$i]=""
i=$((i+1));var[$i]="Other aerosols";brf[$i]=""
i=$((i+1));var[$i]="Other Agricultural residues";brf[$i]="AGRRES"
i=$((i+1));var[$i]="Other agriculture emissions";brf[$i]=""
i=$((i+1));var[$i]="Other Applications";brf[$i]=""
i=$((i+1));var[$i]="Other Bituminous Coal";brf[$i]=""
i=$((i+1));var[$i]="Other Carbon-containing Fertilizers";brf[$i]="3I"
i=$((i+1));var[$i]="Other cereals";brf[$i]="OCER"
i=$((i+1));var[$i]="Other chemical industry";brf[$i]=""
i=$((i+1));var[$i]="Other CO2 transport and storage";brf[$i]=""
i=$((i+1));var[$i]="Other direct NO2 from managed Soils";brf[$i]="OMANSOILS"
i=$((i+1));var[$i]="Other Disposal";brf[$i]=""
i=$((i+1));var[$i]="Other electronics industry";brf[$i]=""
i=$((i+1));var[$i]="Other emissions from energy production";brf[$i]=""
i=$((i+1));var[$i]="Other Fluorochemical Production";brf[$i]=""
i=$((i+1));var[$i]="Other Fossil Fuels";brf[$i]=""
i=$((i+1));var[$i]="Other fugitive emission";brf[$i]=""
i=$((i+1));var[$i]="Other Gaseous Fossil";brf[$i]=""
i=$((i+1));var[$i]="Other Industrial Process and Product Use";brf[$i]=""
i=$((i+1));var[$i]="Other Iron and Steel Production";brf[$i]=""
i=$((i+1));var[$i]="Other Kerosene";brf[$i]=""
i=$((i+1));var[$i]="Other Land";brf[$i]=""
i=$((i+1));var[$i]="Other Land";brf[$i]="OLAND"
i=$((i+1));var[$i]="Other Liquid Fossil";brf[$i]=""
i=$((i+1));var[$i]="Other Liquid Fuels";brf[$i]=""
i=$((i+1));var[$i]="Other livestock";brf[$i]="OANIM"
i=$((i+1));var[$i]="Other LULUCF";brf[$i]=""
i=$((i+1));var[$i]="Other Manufacturing Industries and Constructions";brf[$i]=""
i=$((i+1));var[$i]="Other Metal Industry";brf[$i]=""
i=$((i+1));var[$i]="Other Mineral Soils";brf[$i]="OMINS"
i=$((i+1));var[$i]="Other N2O from product use";brf[$i]=""
i=$((i+1));var[$i]="Other non energy products";brf[$i]=""
i=$((i+1));var[$i]="Other non pipeline transport";brf[$i]=""
i=$((i+1));var[$i]="Other non-fossil fuels (biogenic waste)";brf[$i]=""
i=$((i+1));var[$i]="Other Oil";brf[$i]=""
i=$((i+1));var[$i]="Other operation on oil";brf[$i]=""
i=$((i+1));var[$i]="Other operations on natural gas";brf[$i]=""
i=$((i+1));var[$i]="Other Organic Fertilizers Applied to Soils";brf[$i]="OORGFERT"
i=$((i+1));var[$i]="Other Organic Soils";brf[$i]="OHIST"
i=$((i+1));var[$i]="Other Other Industrial Process and Product Use";brf[$i]=""
i=$((i+1));var[$i]="Other Other Livestock";brf[$i]="OOANIM"
i=$((i+1));var[$i]="Other Other non energy products";brf[$i]=""
i=$((i+1));var[$i]="Other Other petrochemical production";brf[$i]=""
i=$((i+1));var[$i]="Other Other Sectors";brf[$i]=""
i=$((i+1));var[$i]="Other petrochemical production";brf[$i]=""
i=$((i+1));var[$i]="Other Process Uses of Carbonates";brf[$i]=""
i=$((i+1));var[$i]="Other Product Manufacture and Use";brf[$i]=""
i=$((i+1));var[$i]="Other Pulses";brf[$i]="OPULS"
i=$((i+1));var[$i]="Other Rice Cultivation";brf[$i]="3C4"
i=$((i+1));var[$i]="Other Road Transportation";brf[$i]=""
i=$((i+1));var[$i]="Other Sector";brf[$i]=""
i=$((i+1));var[$i]="Other Sectors";brf[$i]=""
i=$((i+1));var[$i]="Other Sheep";brf[$i]="OSHEP"
i=$((i+1));var[$i]="Other Solid Fossil";brf[$i]=""
i=$((i+1));var[$i]="Other Solid fuel operation";brf[$i]=""
i=$((i+1));var[$i]="Other source";brf[$i]="OSOURCE"
i=$((i+1));var[$i]="Other Swine";brf[$i]="OSWIN"
i=$((i+1));var[$i]="Other transport of CO2";brf[$i]=""
i=$((i+1));var[$i]="Other Transportation";brf[$i]=""
i=$((i+1));var[$i]="Other Tubers and Roots";brf[$i]="OTURO"
i=$((i+1));var[$i]="Other unspecifed product manufacture and use";brf[$i]=""
i=$((i+1));var[$i]="Other unspecified uses of carbonates";brf[$i]=""
i=$((i+1));var[$i]="Other uses of Soda Ash";brf[$i]=""
i=$((i+1));var[$i]="Other Wastes";brf[$i]=""
i=$((i+1));var[$i]="Other Wastewater";brf[$i]=""
i=$((i+1));var[$i]="Other Wetlands";brf[$i]="OWETL"
i=$((i+1));var[$i]="Other";brf[$i]="OTHE"
i=$((i+1));var[$i]="Paper and Paperboard";brf[$i]=""
i=$((i+1));var[$i]="Paraffin Wax Use";brf[$i]=""
i=$((i+1));var[$i]="Pasture range and paddock";brf[$i]="PRP"
i=$((i+1));var[$i]="Peat Extraction";brf[$i]="PEATX"
i=$((i+1));var[$i]="Peat";brf[$i]="PEAT"
i=$((i+1));var[$i]="Peatland";brf[$i]="PEATL"
i=$((i+1));var[$i]="Pellet";brf[$i]=""
i=$((i+1));var[$i]="Petrochemical and Carbon Black Production";brf[$i]=""
i=$((i+1));var[$i]="Petroleum Coke";brf[$i]=""
i=$((i+1));var[$i]="Petroleum Refining";brf[$i]=""
i=$((i+1));var[$i]="PFCs";brf[$i]="PFCs"
i=$((i+1));var[$i]="Photovoltaics";brf[$i]=""
i=$((i+1));var[$i]="Pig Iron";brf[$i]=""
i=$((i+1));var[$i]="Pipeline Transport";brf[$i]=""
i=$((i+1));var[$i]="Pipelines";brf[$i]=""
i=$((i+1));var[$i]="PJ";brf[$i]="PJ"
i=$((i+1));var[$i]="Population";brf[$i]="AD"
i=$((i+1));var[$i]="Post-Mining Activities";brf[$i]=""
i=$((i+1));var[$i]="Pregnant";brf[$i]="PREGNANT"
i=$((i+1));var[$i]="Prescribed Burning of Savannas";brf[$i]=""
i=$((i+1));var[$i]="Processing";brf[$i]=""
i=$((i+1));var[$i]="Product Uses as Substitutes for ODS";brf[$i]=""
i=$((i+1));var[$i]="Production";brf[$i]=""
i=$((i+1));var[$i]="Production";brf[$i]="PROD"
i=$((i+1));var[$i]="Protein consumption";brf[$i]=""
i=$((i+1));var[$i]="Public Electricity and Heat Production";brf[$i]=""
i=$((i+1));var[$i]="Pulp Paper and Print";brf[$i]=""
i=$((i+1));var[$i]="Pulses";brf[$i]="PULS"
i=$((i+1));var[$i]="Railways";brf[$i]=""
i=$((i+1));var[$i]="Rainfed";brf[$i]="3C2"
i=$((i+1));var[$i]="Recovery";brf[$i]=""
i=$((i+1));var[$i]="Recovery\/Flaring";brf[$i]=""
i=$((i+1));var[$i]="Reference approach";brf[$i]=""
i=$((i+1));var[$i]="Refinery Feedstocks";brf[$i]=""
i=$((i+1));var[$i]="Refining \/ Storage";brf[$i]=""
i=$((i+1));var[$i]="Refrigeration and Air conditioning";brf[$i]=""
i=$((i+1));var[$i]="Remaining Cropland";brf[$i]=""
i=$((i+1));var[$i]="Remaining Forest land (managed)";brf[$i]=""
i=$((i+1));var[$i]="Remaining Forest land (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Remaining Forest land";brf[$i]=""
i=$((i+1));var[$i]="Remaining Grassland (managed)";brf[$i]=""
i=$((i+1));var[$i]="Remaining Grassland (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Remaining Grassland";brf[$i]=""
i=$((i+1));var[$i]="Remaining Other land";brf[$i]=""
i=$((i+1));var[$i]="Remaining Settlements";brf[$i]=""
i=$((i+1));var[$i]="Remaining Total unmanaged land";brf[$i]=""
i=$((i+1));var[$i]="Remaining Wetlands (managed)";brf[$i]=""
i=$((i+1));var[$i]="Remaining Wetlands (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Remaining Wetlands";brf[$i]=""
i=$((i+1));var[$i]="Reported under";brf[$i]=""
i=$((i+1));var[$i]="Residential";brf[$i]=""
i=$((i+1));var[$i]="Residual Fuel Oil";brf[$i]=""
i=$((i+1));var[$i]="Residue\/ Crop ratio";brf[$i]="RRESCROP"
i=$((i+1));var[$i]="Revegetation";brf[$i]=""
i=$((i+1));var[$i]="Rewetted Mineral Soils";brf[$i]="MINSRW"
i=$((i+1));var[$i]="Rewetted Organic Soils";brf[$i]=""
i=$((i+1));var[$i]="Rewetted Organic Soils";brf[$i]="HISTRW"
i=$((i+1));var[$i]="Rice Cultivation";brf[$i]="3C"
i=$((i+1));var[$i]="Road Transportation";brf[$i]=""
i=$((i+1));var[$i]="Salvage logging";brf[$i]=""
i=$((i+1));var[$i]="Sawnwood";brf[$i]=""
i=$((i+1));var[$i]="Sectoral approach";brf[$i]=""
i=$((i+1));var[$i]="Sectors\/Totals";brf[$i]=""
i=$((i+1));var[$i]="Semi-aerobic";brf[$i]=""
i=$((i+1));var[$i]="Settlements";brf[$i]=""
i=$((i+1));var[$i]="Settlements";brf[$i]="SETTL"
i=$((i+1));var[$i]="Sewage Sludge Applied to Soils";brf[$i]="SEWAGE"
i=$((i+1));var[$i]="SF6 and PFCs from Other Product Use";brf[$i]=""
i=$((i+1));var[$i]="SF6";brf[$i]="SF6"
i=$((i+1));var[$i]="Shale Oil";brf[$i]=""
i=$((i+1));var[$i]="Sheep";brf[$i]="SHEP"
i=$((i+1));var[$i]="Ships";brf[$i]=""
i=$((i+1));var[$i]="Silicon Carbide";brf[$i]=""
i=$((i+1));var[$i]="Single Aeration";brf[$i]="3C1b1"
i=$((i+1));var[$i]="Sinter";brf[$i]=""
i=$((i+1));var[$i]="Sludge removed";brf[$i]=""
i=$((i+1));var[$i]="SO2";brf[$i]="SO2"
i=$((i+1));var[$i]="Soda Ash Production";brf[$i]=""
i=$((i+1));var[$i]="Soils";brf[$i]="SOILS"
i=$((i+1));var[$i]="Solid Biomass";brf[$i]=""
i=$((i+1));var[$i]="Solid Fuel Transformation";brf[$i]=""
i=$((i+1));var[$i]="Solid Fuels";brf[$i]=""
i=$((i+1));var[$i]="Solid storage and dry lot";brf[$i]="SOLID"
i=$((i+1));var[$i]="Solid Waste Disposal";brf[$i]=""
i=$((i+1));var[$i]="Solid Wood";brf[$i]=""
i=$((i+1));var[$i]="Solvents";brf[$i]=""
i=$((i+1));var[$i]="Source apparent consumption";brf[$i]=""
i=$((i+1));var[$i]="Stationary Air-Conditioning";brf[$i]=""
i=$((i+1));var[$i]="Stationary combustion";brf[$i]="SCOMB"
i=$((i+1));var[$i]="Steel";brf[$i]=""
i=$((i+1));var[$i]="Stock change";brf[$i]=""
i=$((i+1));var[$i]="Storage";brf[$i]=""
i=$((i+1));var[$i]="Sub-bituminous Coal";brf[$i]=""
i=$((i+1));var[$i]="Subsequent removals in inventory year";brf[$i]=""
i=$((i+1));var[$i]="Sugar Cane";brf[$i]="SUGC"
i=$((i+1));var[$i]="Surface Mines";brf[$i]=""
i=$((i+1));var[$i]="Swine";brf[$i]="SWIN"
i=$((i+1));var[$i]="t C";brf[$i]="t C"
i=$((i+1));var[$i]="t C\/ha";brf[$i]="t C\/ha"
i=$((i+1));var[$i]="t CO2 equivalent";brf[$i]="t CO2eq"
i=$((i+1));var[$i]="t CO2-C\/t";brf[$i]="t CO2-C\/t"
i=$((i+1));var[$i]="t dm\/ha";brf[$i]="t dm\/ha"
i=$((i+1));var[$i]="t";brf[$i]="t"
i=$((i+1));var[$i]="t\/ha";brf[$i]="t\/ha"
i=$((i+1));var[$i]="t\/t";brf[$i]="t\/t"
i=$((i+1));var[$i]="t\/TJ";brf[$i]="t\/TJ"
i=$((i+1));var[$i]="t\/unit";brf[$i]="t\/unit"
i=$((i+1));var[$i]="t\/yr";brf[$i]="t\/yr"
i=$((i+1));var[$i]="Technical correction";brf[$i]=""
i=$((i+1));var[$i]="Temperate";brf[$i]="TEMP"
i=$((i+1));var[$i]="TFT Flat Panel Display";brf[$i]=""
i=$((i+1));var[$i]="Tier 2";brf[$i]="T2"
i=$((i+1));var[$i]="Titanium Dioxide Production";brf[$i]=""
i=$((i+1));var[$i]="TJ";brf[$i]="TJ"
i=$((i+1));var[$i]="TJ\/unit";brf[$i]="TJ\/unit"
i=$((i+1));var[$i]="Total (with LULUCF with indirect)";brf[$i]="TOTLULUCF"
i=$((i+1));var[$i]="Total (with LULUCF)";brf[$i]=""
i=$((i+1));var[$i]="Total (without LULUCF with indirect)";brf[$i]="TOTnoLULUCF"
i=$((i+1));var[$i]="Total (without LULUCF)";brf[$i]=""
i=$((i+1));var[$i]="Total A";brf[$i]=""
i=$((i+1));var[$i]="Total amount captured for storage";brf[$i]=""
i=$((i+1));var[$i]="Total amount of CO2 injected at storage sites";brf[$i]=""
i=$((i+1));var[$i]="Total amount of exports for storage";brf[$i]=""
i=$((i+1));var[$i]="Total amount of fertilizer applied";brf[$i]=""
i=$((i+1));var[$i]="Total amount of imports for storage";brf[$i]=""
i=$((i+1));var[$i]="Total area at the end of the current year";brf[$i]=""
i=$((i+1));var[$i]="Total area at the end of the previous year";brf[$i]=""
i=$((i+1));var[$i]="Total area subject to conversion";brf[$i]=""
i=$((i+1));var[$i]="Total area";brf[$i]=""
i=$((i+1));var[$i]="Total B";brf[$i]=""
i=$((i+1));var[$i]="Total biomass burned";brf[$i]=""
i=$((i+1));var[$i]="Total HWP from Domestic Harvest";brf[$i]=""
i=$((i+1));var[$i]="Total leakage from transport injection and storage";brf[$i]=""
i=$((i+1));var[$i]="Total N excreted";brf[$i]="NEXC"
i=$((i+1));var[$i]="Total N volatilised as NH3 and Nox";brf[$i]="NVOLAT"
i=$((i+1));var[$i]="Total natural disturbances";brf[$i]=""
i=$((i+1));var[$i]="Total organic product";brf[$i]=""
i=$((i+1));var[$i]="Total unmanaged land";brf[$i]=""
i=$((i+1));var[$i]="Transmission and storage";brf[$i]=""
i=$((i+1));var[$i]="Transport of CO2";brf[$i]=""
i=$((i+1));var[$i]="Transport Refrigeration";brf[$i]=""
i=$((i+1));var[$i]="Transport";brf[$i]=""
i=$((i+1));var[$i]="Trigger test";brf[$i]=""
i=$((i+1));var[$i]="Tubers and Roots";brf[$i]="TURO"
i=$((i+1));var[$i]="Type";brf[$i]="TYPE"
i=$((i+1));var[$i]="Typical animal mass (average)";brf[$i]="MASS"
i=$((i+1));var[$i]="Uncategorized Waste Disposal Sites";brf[$i]=""
i=$((i+1));var[$i]="Underground Mines";brf[$i]=""
i=$((i+1));var[$i]="Unit";brf[$i]="UNIT"
i=$((i+1));var[$i]="Unmanaged Waste Disposal Sites";brf[$i]=""
i=$((i+1));var[$i]="unmanaged";brf[$i]=""
i=$((i+1));var[$i]="Unspecified mix of HFCs and PFCs";brf[$i]=""
i=$((i+1));var[$i]="Unspecified mix of HFCs";brf[$i]=""
i=$((i+1));var[$i]="Unspecified mix of PFCs";brf[$i]=""
i=$((i+1));var[$i]="Urea Application";brf[$i]="3H"
i=$((i+1));var[$i]="Urine and Dung Deposited by Grazing Animals";brf[$i]="NGRAZ"
i=$((i+1));var[$i]="Value inscribed in the Appendix to the annex to decision 2\/CMP.7";brf[$i]=""
i=$((i+1));var[$i]="Venting and Flaring";brf[$i]=""
i=$((i+1));var[$i]="Venting";brf[$i]=""
i=$((i+1));var[$i]="Volatilized N from agricultural inputs of N";brf[$i]=""
i=$((i+1));var[$i]="VS daily excretion (average)";brf[$i]="VSEXC"
i=$((i+1));var[$i]="Warm";brf[$i]="WARM"
i=$((i+1));var[$i]="Waste (non-biomass fraction)";brf[$i]=""
i=$((i+1));var[$i]="Waste Composting";brf[$i]=""
i=$((i+1));var[$i]="Waste incineration with energy recovery included as biomass";brf[$i]=""
i=$((i+1));var[$i]="Waste incineration with energy recovery included as fossil fuels";brf[$i]=""
i=$((i+1));var[$i]="Waste Incineration";brf[$i]=""
i=$((i+1));var[$i]="Waste management";brf[$i]=""
i=$((i+1));var[$i]="Waste";brf[$i]=""
i=$((i+1));var[$i]="Wastewater Treatment and Discharge";brf[$i]=""
i=$((i+1));var[$i]="Wastewater";brf[$i]=""
i=$((i+1));var[$i]="Water Depth > 100 cm";brf[$i]="3C3b"
i=$((i+1));var[$i]="Water Depth 50-100 cm";brf[$i]="3C3a"
i=$((i+1));var[$i]="Weight";brf[$i]="WEIGHT"
i=$((i+1));var[$i]="Wetland Drainage and Rewetting";brf[$i]="WETLDRW"
i=$((i+1));var[$i]="Wetlands (managed)";brf[$i]=""
i=$((i+1));var[$i]="Wetlands (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Wetlands";brf[$i]="WETL"
i=$((i+1));var[$i]="Wheat";brf[$i]="WHEA"
i=$((i+1));var[$i]="Wildfires";brf[$i]=""
i=$((i+1));var[$i]="Wood panels";brf[$i]=""
i=$((i+1));var[$i]="Wood product";brf[$i]=""
i=$((i+1));var[$i]="Work";brf[$i]="WORK"
i=$((i+1));var[$i]="yr";brf[$i]="yr"
i=$((i+1));var[$i]="Zinc Production";brf[$i]=""
