i=$((i+1));var[$i]="4(KP)";brf[$i]=""
i=$((i+1));var[$i]="Acrylonitrile";brf[$i]=""
i=$((i+1));var[$i]="Activity Data";brf[$i]="AD"
i=$((i+1));var[$i]="Additional Information (for Tier 2)";brf[$i]="INFOT2"
i=$((i+1));var[$i]="Additional Information for NIR-1";brf[$i]="INFONIR1"
i=$((i+1));var[$i]="Adipic Acid Production";brf[$i]=""
i=$((i+1));var[$i]="Aerosols";brf[$i]=""
i=$((i+1));var[$i]="Agricultural Soils";brf[$i]="4D"
i=$((i+1));var[$i]="Agriculture";brf[$i]="3"
i=$((i+1));var[$i]="Agriculture\/Forestry\/Fishing";brf[$i]=""
i=$((i+1));var[$i]="Aluminium Production";brf[$i]=""
i=$((i+1));var[$i]="Ammonia Production";brf[$i]=""
i=$((i+1));var[$i]="Anaerobic Digestion at Biogas Facilities";brf[$i]=""
i=$((i+1));var[$i]="Anaerobic";brf[$i]=""
i=$((i+1));var[$i]="Annual Change in Total Long-term C Storage in HWP Waste";brf[$i]=""
i=$((i+1));var[$i]="Annual Change in Total Long-term C Storage";brf[$i]=""
i=$((i+1));var[$i]="Biological Treatment of Solid Waste";brf[$i]=""
i=$((i+1));var[$i]="By-Product Emissions";brf[$i]=""
i=$((i+1));var[$i]="By-Product Production";brf[$i]=""
i=$((i+1));var[$i]="Calcium Carbide";brf[$i]=""
i=$((i+1));var[$i]="Caprolactam Glyoxal and Glyoxylic Acid Production";brf[$i]=""
i=$((i+1));var[$i]="Caprolactam";brf[$i]=""
i=$((i+1));var[$i]="Carbide Production";brf[$i]=""
i=$((i+1));var[$i]="Carbon Black";brf[$i]=""
i=$((i+1));var[$i]="Cars";brf[$i]=""
i=$((i+1));var[$i]="Cement Production";brf[$i]=""
i=$((i+1));var[$i]="Ceramics";brf[$i]=""
i=$((i+1));var[$i]="CH4 Emissions";brf[$i]="CH4EM"
i=$((i+1));var[$i]="Chemical Industry";brf[$i]=""
i=$((i+1));var[$i]="Chemicals";brf[$i]=""
i=$((i+1));var[$i]="Closed Cells";brf[$i]=""
i=$((i+1));var[$i]="CO2 Emissions";brf[$i]="CO2EM"
i=$((i+1));var[$i]="CO2 Transport and Storage";brf[$i]=""
i=$((i+1));var[$i]="Coal Mining and Handling";brf[$i]=""
i=$((i+1));var[$i]="Commercial Refrigeration";brf[$i]=""
i=$((i+1));var[$i]="Commercial\/Institutional";brf[$i]=""
i=$((i+1));var[$i]="Comparison of CO2 Emissions from Fuel Combustion";brf[$i]=""
i=$((i+1));var[$i]="Contained";brf[$i]=""
i=$((i+1));var[$i]="Continuously Flooded";brf[$i]="3C1a"
i=$((i+1));var[$i]="Cropland (managed)";brf[$i]=""
i=$((i+1));var[$i]="Cropland";brf[$i]=""
i=$((i+1));var[$i]="Deep Water";brf[$i]="3C3"
i=$((i+1));var[$i]="Direct Reduced Iron";brf[$i]=""
i=$((i+1));var[$i]="Dolomite CaMg(CO3)2";brf[$i]=""
i=$((i+1));var[$i]="Domestic Aviation";brf[$i]=""
i=$((i+1));var[$i]="Domestic Navigation";brf[$i]=""
i=$((i+1));var[$i]="Domestic Refrigeration";brf[$i]=""
i=$((i+1));var[$i]="Drought Prone";brf[$i]="3C2b"
i=$((i+1));var[$i]="Electrical Equipment";brf[$i]=""
i=$((i+1));var[$i]="Electronics Industry";brf[$i]=""
i=$((i+1));var[$i]="Emissive";brf[$i]=""
i=$((i+1));var[$i]="Energy Industries";brf[$i]=""
i=$((i+1));var[$i]="Energy";brf[$i]=""
i=$((i+1));var[$i]="Enteric Fermentation";brf[$i]="3A"
i=$((i+1));var[$i]="Ethylene Dichloride and Vinyl Chloride Monomer";brf[$i]=""
i=$((i+1));var[$i]="Ethylene Oxide";brf[$i]=""
i=$((i+1));var[$i]="Ethylene";brf[$i]=""
i=$((i+1));var[$i]="Feedstocks reductants and other non-energy use of fuels";brf[$i]=""
i=$((i+1));var[$i]="Ferroalloys Production";brf[$i]=""
i=$((i+1));var[$i]="F-gases used in foundries";brf[$i]=""
i=$((i+1));var[$i]="Field Burning of Agricultural Residues";brf[$i]="3F"
i=$((i+1));var[$i]="Fire Protection";brf[$i]=""
i=$((i+1));var[$i]="Flaring";brf[$i]=""
i=$((i+1));var[$i]="Flood Prone";brf[$i]="3C2a"
i=$((i+1));var[$i]="Fluorochemical Production";brf[$i]=""
i=$((i+1));var[$i]="Foam Blowing Agents";brf[$i]=""
i=$((i+1));var[$i]="Food Processing Beverages and Tobacco";brf[$i]=""
i=$((i+1));var[$i]="Forest land (managed)";brf[$i]=""
i=$((i+1));var[$i]="Forest land (specify ecological zone)";brf[$i]=""
i=$((i+1));var[$i]="Forest land (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Forest Land";brf[$i]=""
i=$((i+1));var[$i]="Fuel Combustion - Reference Approach";brf[$i]=""
i=$((i+1));var[$i]="Fuel Combustion - Sectoral approach";brf[$i]=""
i=$((i+1));var[$i]="Fugitive Emissions from Fuels";brf[$i]=""
i=$((i+1));var[$i]="Fugitive Emissions";brf[$i]=""
i=$((i+1));var[$i]="Glass production";brf[$i]=""
i=$((i+1));var[$i]="Glyoxal";brf[$i]=""
i=$((i+1));var[$i]="Glyoxylic Acid";brf[$i]=""
i=$((i+1));var[$i]="Grassland (managed)";brf[$i]=""
i=$((i+1));var[$i]="Grassland (specify ecological zone)";brf[$i]=""
i=$((i+1));var[$i]="Grassland (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Grassland";brf[$i]=""
i=$((i+1));var[$i]="Harvested Wood Products";brf[$i]=""
i=$((i+1));var[$i]="Heat Transfer Fluid";brf[$i]=""
i=$((i+1));var[$i]="Heavy duty trucks and buses";brf[$i]=""
i=$((i+1));var[$i]="HWP Produced and Consumed Domestically";brf[$i]=""
i=$((i+1));var[$i]="HWP Produced and Exported";brf[$i]=""
i=$((i+1));var[$i]="Incineration and Open Burning of Waste";brf[$i]=""
i=$((i+1));var[$i]="Indirect N2O Emissions";brf[$i]=""
i=$((i+1));var[$i]="Industrial Processes and Product Use";brf[$i]=""
i=$((i+1));var[$i]="Industrial Refrigeration";brf[$i]=""
i=$((i+1));var[$i]="Injection and Storage";brf[$i]=""
i=$((i+1));var[$i]="Injection";brf[$i]=""
i=$((i+1));var[$i]="Integrated Circuit or Semiconductor";brf[$i]=""
i=$((i+1));var[$i]="Intermittently Flooded";brf[$i]="3C1b"
i=$((i+1));var[$i]="International Aviation";brf[$i]=""
i=$((i+1));var[$i]="International Bunkers";brf[$i]=""
i=$((i+1));var[$i]="International Navigation";brf[$i]=""
i=$((i+1));var[$i]="Iron and Steel Production";brf[$i]=""
i=$((i+1));var[$i]="Iron and Steel";brf[$i]=""
i=$((i+1));var[$i]="Irrigated";brf[$i]="3C1"
i=$((i+1));var[$i]="Land Transition Matrix";brf[$i]=""
i=$((i+1));var[$i]="Land Use Land-Use Change and Forestry";brf[$i]=""
i=$((i+1));var[$i]="Lead Production";brf[$i]=""
i=$((i+1));var[$i]="Light duty trucks";brf[$i]=""
i=$((i+1));var[$i]="Lime Production";brf[$i]=""
i=$((i+1));var[$i]="Limestone CaCO3";brf[$i]=""
i=$((i+1));var[$i]="Liming";brf[$i]="3G"
i=$((i+1));var[$i]="Livestock";brf[$i]=""
i=$((i+1));var[$i]="Long-term Storage of C in Waste Disposal Sites";brf[$i]=""
i=$((i+1));var[$i]="Lubricant Use";brf[$i]=""
i=$((i+1));var[$i]="Magnesium Production";brf[$i]=""
i=$((i+1));var[$i]="Managed Waste Disposal Sites";brf[$i]=""
i=$((i+1));var[$i]="Manufacture of Solid Fuels and Other Energy Industries";brf[$i]=""
i=$((i+1));var[$i]="Manufacturing Industries and Construction";brf[$i]=""
i=$((i+1));var[$i]="Manure Management";brf[$i]="3B"
i=$((i+1));var[$i]="Medical Applications";brf[$i]=""
i=$((i+1));var[$i]="Metal Industry";brf[$i]=""
i=$((i+1));var[$i]="Metered Dose Inhalers";brf[$i]=""
i=$((i+1));var[$i]="Methanol";brf[$i]=""
i=$((i+1));var[$i]="Mineral Industry";brf[$i]=""
i=$((i+1));var[$i]="Mobile Air-Conditioning";brf[$i]=""
i=$((i+1));var[$i]="Motorcycles";brf[$i]=""
i=$((i+1));var[$i]="Multilateral Operations";brf[$i]=""
i=$((i+1));var[$i]="Multiple aeration";brf[$i]="3C1b2"
i=$((i+1));var[$i]="N2O and NMVOC Emissions";brf[$i]=""
i=$((i+1));var[$i]="N2O Emissions per MMS";brf[$i]="N2OEM"
i=$((i+1));var[$i]="N2O from Product Uses";brf[$i]=""
i=$((i+1));var[$i]="Natural Gas";brf[$i]=""
i=$((i+1));var[$i]="NIR-1";brf[$i]="NIR1"
i=$((i+1));var[$i]="NIR-2";brf[$i]="NIR2"
i=$((i+1));var[$i]="NIR-2.1";brf[$i]="NIR2.1"
i=$((i+1));var[$i]="Nitric Acid Production";brf[$i]=""
i=$((i+1));var[$i]="Non-energy Products from Fuels and Solvent Use";brf[$i]=""
i=$((i+1));var[$i]="Non-Ferrous Metals";brf[$i]=""
i=$((i+1));var[$i]="Non-metallic minerals";brf[$i]=""
i=$((i+1));var[$i]="Non-metallurgical Magnesium Production";brf[$i]=""
i=$((i+1));var[$i]="Oil and Natural Gas and Other Emissions from Energy Production";brf[$i]=""
i=$((i+1));var[$i]="Oil";brf[$i]=""
i=$((i+1));var[$i]="Open Burning of Waste";brf[$i]=""
i=$((i+1));var[$i]="Open Cells";brf[$i]=""
i=$((i+1));var[$i]="Other aerosols";brf[$i]=""
i=$((i+1));var[$i]="Other agriculture emissions";brf[$i]=""
i=$((i+1));var[$i]="Other Applications";brf[$i]=""
i=$((i+1));var[$i]="Other Carbon-containing Fertilizers";brf[$i]="3I"
i=$((i+1));var[$i]="Other chemical industry";brf[$i]=""
i=$((i+1));var[$i]="Other CO2 transport and storage";brf[$i]=""
i=$((i+1));var[$i]="Other Disposal";brf[$i]=""
i=$((i+1));var[$i]="Other electronics industry";brf[$i]=""
i=$((i+1));var[$i]="Other emissions from energy production";brf[$i]=""
i=$((i+1));var[$i]="Other Fluorochemical Production";brf[$i]=""
i=$((i+1));var[$i]="Other fugitive emission";brf[$i]=""
i=$((i+1));var[$i]="Other Industrial Process and Product Use";brf[$i]=""
i=$((i+1));var[$i]="Other Iron and Steel Production";brf[$i]=""
i=$((i+1));var[$i]="Other Land";brf[$i]=""
i=$((i+1));var[$i]="Other LULUCF";brf[$i]=""
i=$((i+1));var[$i]="Other Manufacturing Industries and Constructions";brf[$i]=""
i=$((i+1));var[$i]="Other Metal Industry";brf[$i]=""
i=$((i+1));var[$i]="Other N2O from product use";brf[$i]=""
i=$((i+1));var[$i]="Other non energy products";brf[$i]=""
i=$((i+1));var[$i]="Other non pipeline transport";brf[$i]=""
i=$((i+1));var[$i]="Other Other Industrial Process and Product Use";brf[$i]=""
i=$((i+1));var[$i]="Other Other non energy products";brf[$i]=""
i=$((i+1));var[$i]="Other Other petrochemical production";brf[$i]=""
i=$((i+1));var[$i]="Other Other Sectors";brf[$i]=""
i=$((i+1));var[$i]="Other petrochemical production";brf[$i]=""
i=$((i+1));var[$i]="Other Process Uses of Carbonates";brf[$i]=""
i=$((i+1));var[$i]="Other Product Manufacture and Use";brf[$i]=""
i=$((i+1));var[$i]="Other Rice Cultivation";brf[$i]="3C4"
i=$((i+1));var[$i]="Other Road Transportation";brf[$i]=""
i=$((i+1));var[$i]="Other Sector";brf[$i]=""
i=$((i+1));var[$i]="Other Sectors";brf[$i]=""
i=$((i+1));var[$i]="Other Solid fuel operation";brf[$i]=""
i=$((i+1));var[$i]="Other transport of CO2";brf[$i]=""
i=$((i+1));var[$i]="Other Transportation";brf[$i]=""
i=$((i+1));var[$i]="Other unspecifed product manufacture and use";brf[$i]=""
i=$((i+1));var[$i]="Other unspecified uses of carbonates";brf[$i]=""
i=$((i+1));var[$i]="Other uses of Soda Ash";brf[$i]=""
i=$((i+1));var[$i]="Paraffin Wax Use";brf[$i]=""
i=$((i+1));var[$i]="Pellet";brf[$i]=""
i=$((i+1));var[$i]="Petrochemical and Carbon Black Production";brf[$i]=""
i=$((i+1));var[$i]="Petroleum Refining";brf[$i]=""
i=$((i+1));var[$i]="Photovoltaics";brf[$i]=""
i=$((i+1));var[$i]="Pig Iron";brf[$i]=""
i=$((i+1));var[$i]="Pipeline Transport";brf[$i]=""
i=$((i+1));var[$i]="Pipelines";brf[$i]=""
i=$((i+1));var[$i]="Prescribed Burning of Savannas";brf[$i]=""
i=$((i+1));var[$i]="Product Uses as Substitutes for ODS";brf[$i]=""
i=$((i+1));var[$i]="Public Electricity and Heat Production";brf[$i]=""
i=$((i+1));var[$i]="Pulp Paper and Print";brf[$i]=""
i=$((i+1));var[$i]="Railways";brf[$i]=""
i=$((i+1));var[$i]="Rainfed";brf[$i]="3C2"
i=$((i+1));var[$i]="Reference approach";brf[$i]=""
i=$((i+1));var[$i]="Refrigeration and Air conditioning";brf[$i]=""
i=$((i+1));var[$i]="Residential";brf[$i]=""
i=$((i+1));var[$i]="Rice Cultivation";brf[$i]="3C"
i=$((i+1));var[$i]="Road Transportation";brf[$i]=""
i=$((i+1));var[$i]="Sectoral approach";brf[$i]=""
i=$((i+1));var[$i]="Sectors\/Totals";brf[$i]=""
i=$((i+1));var[$i]="Semi-aerobic";brf[$i]=""
i=$((i+1));var[$i]="Settlements";brf[$i]=""
i=$((i+1));var[$i]="SF6 and PFCs from Other Product Use";brf[$i]=""
i=$((i+1));var[$i]="Ships";brf[$i]=""
i=$((i+1));var[$i]="Silicon Carbide";brf[$i]=""
i=$((i+1));var[$i]="Single Aeration";brf[$i]="3C1b1"
i=$((i+1));var[$i]="Sinter";brf[$i]=""
i=$((i+1));var[$i]="Soda Ash Production";brf[$i]=""
i=$((i+1));var[$i]="Solid Fuel Transformation";brf[$i]=""
i=$((i+1));var[$i]="Solid Fuels";brf[$i]=""
i=$((i+1));var[$i]="Solid Waste Disposal";brf[$i]=""
i=$((i+1));var[$i]="Solvents";brf[$i]=""
i=$((i+1));var[$i]="Stationary Air-Conditioning";brf[$i]=""
i=$((i+1));var[$i]="Steel";brf[$i]=""
i=$((i+1));var[$i]="Storage";brf[$i]=""
i=$((i+1));var[$i]="Surface Mines";brf[$i]=""
i=$((i+1));var[$i]="TFT Flat Panel Display";brf[$i]=""
i=$((i+1));var[$i]="Titanium Dioxide Production";brf[$i]=""
i=$((i+1));var[$i]="Total (with LULUCF with indirect)";brf[$i]="TOTLULUCF"
i=$((i+1));var[$i]="Total (without LULUCF with indirect)";brf[$i]="TOTnoLULUCF"
i=$((i+1));var[$i]="Total A";brf[$i]=""
i=$((i+1));var[$i]="Total amount captured for storage";brf[$i]=""
i=$((i+1));var[$i]="Total amount of CO2 injected at storage sites";brf[$i]=""
i=$((i+1));var[$i]="Total amount of exports for storage";brf[$i]=""
i=$((i+1));var[$i]="Total amount of imports for storage";brf[$i]=""
i=$((i+1));var[$i]="Total B";brf[$i]=""
i=$((i+1));var[$i]="Total HWP from Domestic Harvest";brf[$i]=""
i=$((i+1));var[$i]="Total leakage from transport injection and storage";brf[$i]=""
i=$((i+1));var[$i]="Transport of CO2";brf[$i]=""
i=$((i+1));var[$i]="Transport Refrigeration";brf[$i]=""
i=$((i+1));var[$i]="Transport";brf[$i]=""
i=$((i+1));var[$i]="Uncategorized Waste Disposal Sites";brf[$i]=""
i=$((i+1));var[$i]="Underground Mines";brf[$i]=""
i=$((i+1));var[$i]="Unmanaged Waste Disposal Sites";brf[$i]=""
i=$((i+1));var[$i]="Urea Application";brf[$i]="3H"
i=$((i+1));var[$i]="Venting and Flaring";brf[$i]=""
i=$((i+1));var[$i]="Venting";brf[$i]=""
i=$((i+1));var[$i]="Waste Composting";brf[$i]=""
i=$((i+1));var[$i]="Waste Incineration";brf[$i]=""
i=$((i+1));var[$i]="Waste management";brf[$i]=""
i=$((i+1));var[$i]="Wastewater Treatment and Discharge";brf[$i]=""
i=$((i+1));var[$i]="Water Depth > 100 cm";brf[$i]="3C3b"
i=$((i+1));var[$i]="Water Depth 50-100 cm";brf[$i]="3C3a"
i=$((i+1));var[$i]="Wetlands (managed)";brf[$i]=""
i=$((i+1));var[$i]="Wetlands (unmanaged)";brf[$i]=""
i=$((i+1));var[$i]="Wetlands";brf[$i]="WETL"
i=$((i+1));var[$i]="Zinc Production";brf[$i]=""
