#Dimension type,Dimension instance name";brf[$i]="Acronym"
i=$((i+1));var[$i]="1.AA-Fuel Combustion - Sectoral Approach";brf[$i]="1A"
i=$((i+1));var[$i]="1.B-Fugitive Emissions from Fuels";brf[$i]="1B"
i=$((i+1));var[$i]="2.A-Mineral Products";brf[$i]="2A"
i=$((i+1));var[$i]="2.B-Chemical Industry";brf[$i]="2B"
i=$((i+1));var[$i]="2.C-Metal Production";brf[$i]="2C"
i=$((i+1));var[$i]="2.D-Other Production";brf[$i]="2D"
i=$((i+1));var[$i]="2.E-Production of Halocarbons and SF6";brf[$i]="2E"
i=$((i+1));var[$i]="2.F-Consumption of Halocarbons and SF6";brf[$i]="2F"
i=$((i+1));var[$i]="2.G-Other (please specify)";brf[$i]="2G"
i=$((i+1));var[$i]="3.A-Paint Application";brf[$i]="3A"
i=$((i+1));var[$i]="3.B-Degreasing and Dry Cleaning";brf[$i]="3B"
i=$((i+1));var[$i]="3.C-Chemical Products, Manufacture and Processing";brf[$i]="3C"
i=$((i+1));var[$i]="3.D-Other";brf[$i]="3D"
i=$((i+1));var[$i]="4.A-Enteric Fermentation";brf[$i]="4A"
i=$((i+1));var[$i]="4.B-Manure Management";brf[$i]="4B"
i=$((i+1));var[$i]="4.C.1.1-Continuously Flooded";brf[$i]="4C11"
i=$((i+1));var[$i]="4.C.1.2.1-Single Aeration";brf[$i]="4C121"
i=$((i+1));var[$i]="4.C.1.2.2-Multiple Aeration";brf[$i]="4C122"
i=$((i+1));var[$i]="4.C.1.2-Intermittently Flooded";brf[$i]="4C12"
i=$((i+1));var[$i]="4.C.1-Irrigated";brf[$i]="4C1"
i=$((i+1));var[$i]="4.C.2.1-Flood Prone";brf[$i]="4C21"
i=$((i+1));var[$i]="4.C.2.2-Drought Prone";brf[$i]="4C22"
i=$((i+1));var[$i]="4.C.2-Rainfed";brf[$i]="4C2"
i=$((i+1));var[$i]="4.C.3.1-Water Depth 50-100 cm";brf[$i]="4C31"
i=$((i+1));var[$i]="4.C.3.2-Water Depth > 100 cm";brf[$i]="4C32"
i=$((i+1));var[$i]="4.C.3-Deep Water";brf[$i]="4C3"
i=$((i+1));var[$i]="4.C.4-Other (please specify)";brf[$i]="4C4"
i=$((i+1));var[$i]="4.C-Rice Cultivation";brf[$i]="4C"
i=$((i+1));var[$i]="4.D.1.1-Synthetic Fertilizers";brf[$i]="4D11"
i=$((i+1));var[$i]="4.D.1.2-Animal Manure Applied to Soils";brf[$i]="4D12"
i=$((i+1));var[$i]="4.D.1.3-N-fixing Crops";brf[$i]="4D13"
i=$((i+1));var[$i]="4.D.1.4-Crop Residue";brf[$i]="4D14"
i=$((i+1));var[$i]="4.D.1.5-Cultivation of Histosols";brf[$i]="4D15"
i=$((i+1));var[$i]="4.D.1.6-Other direct emissions (please specify)";brf[$i]="4D16"
i=$((i+1));var[$i]="4.D.1-Direct Soil Emissions";brf[$i]="4D1"
i=$((i+1));var[$i]="4.D.2-Pasture, Range and Paddock Manure";brf[$i]="4D2"
i=$((i+1));var[$i]="4.D.3.1-Atmospheric Deposition";brf[$i]="4D31"
i=$((i+1));var[$i]="4.D.3.2-Nitrogen Leaching and Run-off";brf[$i]="4D32"
i=$((i+1));var[$i]="4.D.3-Indirect Emissions";brf[$i]="4D3"
i=$((i+1));var[$i]="4.D.4-Other (please specify)";brf[$i]="4D4"
i=$((i+1));var[$i]="4.D-Agricultural Soils";brf[$i]="4D"
i=$((i+1));var[$i]="4.E.1-specify ecological zone";brf[$i]="4.00E+01"
i=$((i+1));var[$i]="4.E-Prescribed Burning of Savannas";brf[$i]="4E"
i=$((i+1));var[$i]="4.F.1.1-Wheat";brf[$i]="4F11"
i=$((i+1));var[$i]="4.F.1.2-Barley";brf[$i]="4F12"
i=$((i+1));var[$i]="4.F.1.3-Maize";brf[$i]="4F13"
i=$((i+1));var[$i]="4.F.1.4-Oats";brf[$i]="4F14"
i=$((i+1));var[$i]="4.F.1.5-Rye";brf[$i]="4F15"
i=$((i+1));var[$i]="4.F.1.6-Rice";brf[$i]="4F16"
i=$((i+1));var[$i]="4.F.1.7-Other (please specify)";brf[$i]="4F17"
i=$((i+1));var[$i]="4.F.2.1-Dry bean";brf[$i]="4F21"
i=$((i+1));var[$i]="4.F.2.2-Peas";brf[$i]="4F22"
i=$((i+1));var[$i]="4.F.2.3-Soybeans";brf[$i]="4F23"
i=$((i+1));var[$i]="4.F.2.4-Other (please specify)";brf[$i]="4F24"
i=$((i+1));var[$i]="4.F.2-Pulse";brf[$i]="4F2"
i=$((i+1));var[$i]="4.F.1-Cereals";brf[$i]="4F1"
i=$((i+1));var[$i]="4.F.3.1-Potatoes";brf[$i]="4F31"
i=$((i+1));var[$i]="4.F.3.2-Other (please specify)";brf[$i]="4F32"
i=$((i+1));var[$i]="4.F.3-Tuber and Root";brf[$i]="4F3"
i=$((i+1));var[$i]="4.F.4-Sugar Cane";brf[$i]="4F4"
i=$((i+1));var[$i]="4.F.5-Other (please specify)";brf[$i]="4F5"
i=$((i+1));var[$i]="4.F-Field Burning of Agricultural Residues";brf[$i]="4F"
i=$((i+1));var[$i]="4.G-Other (please specify)";brf[$i]="4G"
i=$((i+1));var[$i]="All Fuels";brf[$i]="FUEL"
i=$((i+1));var[$i]="All Livestock";brf[$i]="LVST"
i=$((i+1));var[$i]="Buffalo";brf[$i]="BUFF"
i=$((i+1));var[$i]="Camels and Llamas";brf[$i]="CMLL"
i=$((i+1));var[$i]="Mature Non-Dairy Cattle";brf[$i]="MNDAI"
i=$((i+1));var[$i]="Mature Dairy Cattle";brf[$i]="MDAIR"
i=$((i+1));var[$i]="Non-Dairy Cattle";brf[$i]="NDAI"
i=$((i+1));var[$i]="Dairy Cattle";brf[$i]="DAIR"
i=$((i+1));var[$i]="Young Cattle";brf[$i]="YCAT"
i=$((i+1));var[$i]="Cattle";brf[$i]="CATT"
i=$((i+1));var[$i]="Goats";brf[$i]="GOAT"
i=$((i+1));var[$i]="Horses";brf[$i]="HORS"
i=$((i+1));var[$i]="Mules and Asses";brf[$i]="MLAS"
i=$((i+1));var[$i]="Other livestock (please specify)";brf[$i]="OLVST"
i=$((i+1));var[$i]="Poultry";brf[$i]="POUL"
i=$((i+1));var[$i]="Sheep";brf[$i]="SHEE"
i=$((i+1));var[$i]="Swine";brf[$i]="SWIN"
i=$((i+1));var[$i]="Anaerobic lagoon";brf[$i]="ANLAG"
i=$((i+1));var[$i]="Liquid system";brf[$i]="LIQSY"
i=$((i+1));var[$i]="Other AWMS";brf[$i]="OAWMS"
i=$((i+1));var[$i]="Solid storage and dry lot";brf[$i]="SOLID"
i=$((i+1));var[$i]="Emissions";brf[$i]="EM"
i=$((i+1));var[$i]="Implied emission factor";brf[$i]="IEF"
i=$((i+1));var[$i]="Activity Data";brf[$i]="AD"
i=$((i+1));var[$i]="Aggregate GHGs (CO2, CH4, N2O, HFCs, PFCs, SF6)";brf[$i]="GHG"
i=$((i+1));var[$i]="Please specify gas";brf[$i]="spec"
i=$((i+1));var[$i]="(Gg CO2 equivalent)";brf[$i]="GgCO2eq"
i=$((i+1));var[$i]="(Gg)";brf[$i]="Gg"
i=$((i+1));var[$i]="(kg\/head\/yr)";brf[$i]="kg\/head\/yr"
i=$((i+1));var[$i]="(kg N2O-N\/kg N)";brf[$i]="kgN2O-N\/kgN"
i=$((i+1));var[$i]="(g\/m^2)";brf[$i]="g\/m2"
i=$((i+1));var[$i]="(kg N2O-N\/ha)";brf[$i]="kgN2O-N\/ha"
i=$((i+1));var[$i]="(kg\/t dm)";brf[$i]="kg\/tdm"
i=$((i+1));var[$i]="(kg N\/yr)";brf[$i]="kgN\/yr"
i=$((i+1));var[$i]="(kg N\/yr)";brf[$i]="kgN\/yr"
