```{r yaml,results='hide',warning=FALSE,message=FALSE,echo=FALSE}
# YAML header below
# requires one emply line before and must start with --- and end with --- or ...
# see http://pandoc.org/MANUAL.html#extension-yaml_metadata_block
# see https://en.wikipedia.org/wiki/YAML
# and example https://gist.github.com/bowsersenior/979804
```

---
output:
  word_document:
    fig_caption: yes
    fig_width: 3

  html_document: default

foldertext:
  cursubm: 20190315
  ecirfolder: '../ecir'
  

---
    
```{r setdata,results='hide',warning=FALSE,message=FALSE,echo=FALSE}
source("curplot.r")
source("nirfunctions.r")
source("nircomparisonfunctions.r")
if(require(captioner)==FALSE){install.packages("captioner", repos = "https://cloud.r-project.org"); library(captioner)} else {library(captioner)}
if(require(pander)==FALSE){install.packages("pander", repos = "https://cloud.r-project.org"); library(pander)} else {library(pander)}
#if(require(dplyr)==FALSE){install.packages("dplyr", repos = "https://cloud.r-project.org"); library(dplyr)} else {library(dplyr)}
if(require(png)==FALSE){install.packages("png", repos = "https://cloud.r-project.org"); library(png)} else {library(png)}
if(require(grid)==FALSE){install.packages("grid", repos = "https://cloud.r-project.org"); library(grid)} else {library(grid)}
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('table.emphasize.rownames',TRUE)
panderOptions('graph.nomargin',TRUE)
panderOptions('table.style','rmarkdown')
figs<-captioner(prefix = "Figure ",auto_space = TRUE,levels = 2,type = c("n","n"),infix = ".")
tabs<-captioner(prefix = "Table ",auto_space = TRUE,levels = 2,type = c("n","n"),infix = ".")
#for(i in c(1:5)){figs("sec","");bump(figs,2);bump(tabs,1)}


```

```{r total,results='hide',warning=FALSE,message=FALSE,echo=FALSE}
agriemissions<-agriemissions[!agriemissions$party%in%excludeparty,]
allagri<-allagri[!allagri$party%in%excludeparty,]
seltype<-"Total (with LULUCF)"
seltype<-"" #with indirect
# selclass<-"Total (with LULUCF  with indirect)    " #with indirect
selclass<-"Total (without LULUCF  with indirect)    " #with indirect

selclass<-"Sectors/Totals" #without indirect
seltype<-"Total (without LULUCF)" #without indirect
lastyear<-years[length(years)]
lastyear2<-years[length(years)-1]
firstyear<-years[1]
#alltotals[,years]<-apply(alltotals[,years],2,as.numeric)
alltotalsgwp <- merge(alltotals, gwps, by="gas")
alltotalsgwp <- alltotalsgwp[, (years) := .SD * gwp, .SDcols=years]
totalghg<-alltotals[alltotals$type==seltype &alltotals$classification==selclass & alltotals$gas=="Aggregate GHGs",]
totalch4<-alltotals[alltotals$type==seltype &alltotals$classification==selclass & alltotals$gas=="CH4",]
totaln2o<-alltotals[alltotals$type==seltype &alltotals$classification==selclass & alltotals$gas=="N2O",]
totalco2<-alltotals[alltotals$type==seltype &alltotals$classification==selclass & alltotals$gas=="CO2",]

eutotalghg<-apply(totalghg[, years, with=FALSE],2,sum)
eutotalch4<-apply(totalch4[, years, with=FALSE],2,sum)
eutotaln2o<-apply(totaln2o[, years, with=FALSE],2,sum)
eutotalco2<-apply(totalco2[, years, with=FALSE],2,sum)

#Do consider only direct emissions (no indirect N2O emissions)
agritotalch4<-agriemissions[agriemissions$gas=="CH4"&agriemissions$sector_number=="3",]
agritotaln2o<-agriemissions[agriemissions$gas=="N2O"&agriemissions$sector_number=="3"&
                                agriemissions$measure=="Emissions",]
agritotalco2<-agriemissions[agriemissions$gas=="CO2"&agriemissions$sector_number=="3"&
                                agriemissions$measure=="Emissions",]

eusubm<-"EUC"
eusubml<-eum[which(eu==eusubm)]
eukp<-eusubml
acountry<-curcountries[variable==eusubm & value==1]$code3
if(!is.null(excludeparty)) acountry<-acountry[-which(acountry==excludeparty)]
countriesnoeu<-acountry[!acountry%in%eu]
countrynamesnoex<-as.character(country4sub[country4sub$code3%in%acountry,"code3"])
euagritotalch4<-agritotalch4[agritotalch4$party==eusubm,]
euagritotaln2o<-agritotaln2o[agritotaln2o$party==eusubm,]
euagritotalco2<-agritotalco2[agritotalco2$party==eusubm,]
euagritotalghg<-rbind(euagritotalch4, rbind(euagritotaln2o, euagritotalco2))

flds <- setdiff(names(euagritotalghg), c("gas", "variableUID", "unit", "gwp", years))
euagritotalghg <- euagritotalghg[, lapply(.SD, sum, na.rm=TRUE), .SDcols=years, by=flds]

euagritotalch4 <- as.data.frame(euagritotalch4)
euagritotaln2o <- as.data.frame(euagritotaln2o)
euagritotalco2 <- as.data.frame(euagritotalco2)
euagritotalghg <- as.data.frame(euagritotalghg)
euagritotalghg$gas<-"CO2"
figure<-0
table<-0
```

