### Workshops and activities to improve the quality of the inventory in agriculture

#### Workshop on 'Inventories and Projections of Greenhouse Gas Emissions from Agriculture' (2003)

As a first activity to assure the quality of the inventory by Member States, a workshop on "Inventories and Projections of Greenhouse Gas Emissions from Agriculture" was held at the European Environment Agency in February 2003. The workshop focused on the emissions of methane (CH4) and nitrous oxide (N2O) induced by activities in the agricultural sector, not considering changes of carbon stocks in agricultural soils, but including emissions of ammonia (NH3). The consideration of ammonia emissions allows the validation of the N2O emission sources and it further strengthens the link between greenhouse gas and air pollutant emission inventories reported under the UNFCCC, the EC Climate Change Committee, the UNECE Long-Range Transboundary Air Pollution Convention, and the EU national emission ceiling directive. Objectives of the workshop were to compare the Member States methodologies and to identify and explain the main differences. The longer term objective is to further improve the methods used for inventories and projections in the different Member States and to identify how national and common agricultural policies could be integrated in EU-wide emission scenarios. 

The workshop report including the Recommendations formulated at the workshop are available [here](https://www.researchgate.net/publication/284189570_N2O_emissions_from_agriculture._Report_on_the_expert_meeting_on_improving_the_quality_for_greenhouse_gas_emission_inventories_for_category_4D_Joint_Research_Centre_21-22_October_2004_Ispra?ev=prf_pub)[^2005report]

[^2005report]: &#09;Leip, A., 2005. N2O emissions from agriculture. Report on the expert meeting on 'improving the quality for greenhouse gas emission inventories for category 4D', Joint Research Centre, 21-22 October 2004, Ispra. Office for Official Publication of the European Communities, Luxembourg. doi:http://dx.doi.org/10.13140/RG.2.1.4706.7607.

#### Survey on agricultural production methods (SAPM 2010)

The Survey on agricultural production methods, abbreviated as SAPM, is a once-only survey carried out in 2010 to collect data at farm level on agri-environmental measures. EU Member States could choose whether to carry out the SAPM as a sample survey or as a census survey. Data were collected on tillage methods, soil conservation, landscape features, animal grazing, animal housing, manure application, manure storage and treatment facilities and irrigation. With reference to irrigation, Member States were asked to provide estimation (possibly by means of models) of the volume of water used for irrigation on the agricultural holding. 

The characteristics that were collected are given in the Regulation (EC) No 1166/2008 of the European Parliament and of the Council 19 November 2008 on farm structure surveys[^fss2008] and the survey on agricultural production methods  and further defined in the Commission Regulation (EC) No 1200/2009 of 30  November 2009 implementing Regulation (EC) No 1166/2008 of the European Parliament and of the Council on farm structure surveys and the survey on agricultural production methods, as regards livestock unit coefficients and definitions of the characteristics[^sapm2009].

A list of characteristics of potential relevance for the quantification of GHG emissions is given in `r tabs("sapmcharachteristics","Selected characteristics included in the 'Survey on agricultural production methods' (SAPM)",display="cite")`.

```{r samptable,results='hide',warning=FALSE,message=FALSE,echo=FALSE}
sapm<-as.data.frame(t(c("Animal Grazing","Grazing on holding","Area grazed during the last year","ha")))
sapm<-rbind(sapm,t(c("","","Amount of time when animals are outdoors on pasture","Month per year")))
sapm<-rbind(sapm,t(c("","Common land grazing","Total number of animals grazing on common land","Head")))
sapm<-rbind(sapm,t(c("","","Amount of time when animals are grazing on common land","Month per year")))
sapm<-rbind(sapm,t(c("Animal housing","Cattle","Stanchion-tied table - with solid dung and liquid manure","Places")))
sapm<-rbind(sapm,t(c("","","Stanchion-tied table - with slurry","Places")))
sapm<-rbind(sapm,t(c("","","Loose housing - with solid dung and liquid manure","Places")))
sapm<-rbind(sapm,t(c("","","Loose housing - with slurry","Places")))
sapm<-rbind(sapm,t(c("","","Other","Places")))
sapm<-rbind(sapm,t(c("","Pigs","On partially slatted floors","Places")))
sapm<-rbind(sapm,t(c("","","On completely slatted floors","Places")))
sapm<-rbind(sapm,t(c("","","On straw beds (deep litter housing)","Places")))
sapm<-rbind(sapm,t(c("","","Other","Places")))
sapm<-rbind(sapm,t(c("","Laying hens","On straw beds (deep litter housing)","Places")))
sapm<-rbind(sapm,t(c("","","Battery cage (all types)","Places")))
sapm<-rbind(sapm,t(c("","","&#09;Battery cage with manure belt","Places")))
sapm<-rbind(sapm,t(c("","","&#09;Battery cage with deep pit","Places")))
sapm<-rbind(sapm,t(c("","","&#09;Battery cage with stilt house","Places")))
sapm<-rbind(sapm,t(c("","","Other","Places")))
sapm<-rbind(sapm,t(c("Manure application","Used agricultural area on which solid/farmyard manure is applied","Total","UAA % band (^2^)")))
sapm<-rbind(sapm,t(c("","Used agricultural area on which solid/farmyard manure is applied","With immediate incorporation","UAA % band (^2^)")))
sapm<-rbind(sapm,t(c("","Used agricultural area on which slurry is applied","Total","UAA % band (^2^)")))
sapm<-rbind(sapm,t(c("","Used agricultural area on which slurry is applied","With immediate incorporation","UAA % band (^2^)")))
sapm<-rbind(sapm,t(c("","Percent of the total produced manure exported from the holding","","Percentage band (^3^)")))
sapm<-rbind(sapm,t(c("Manure storage and treatment facilities","Storage facilities for:","Solid dung","Yes/No")))
sapm<-rbind(sapm,t(c("","","Liquid manure","Yes/No")))
sapm<-rbind(sapm,t(c("","","Slurry: Slurry tank","Yes/No")))
sapm<-rbind(sapm,t(c("","","Slurry: Lagoon","Yes/No")))
sapm<-rbind(sapm,t(c("","Are the storage facilities covered?","Solid dung","Yes/No")))
sapm<-rbind(sapm,t(c("","","Solid dung","Yes/No")))
sapm<-rbind(sapm,t(c("","","Slurry","Yes/No")))
names(sapm)<-c("Characteristic","&#09;","&#09;","Units/categories")
```


`r tabs("sapmcharachteristics",display="full")`

`r pander(sapm)`

Note&nbsp;1:&#09;Utilised agricultural area (UAA) percentage band: (0), (> 0-< 25), (=25-< 50), (=50-< 75), (=75)

Note&nbsp;2:&#09;Percentage band: (0), (> 0-< 25), (=25-< 50), (=50-< 75), (=75).


[^fss2008]: &#09;http://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:32008R1166
[^sapm2009]: &#09;http://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1448050507039&uri=CELEX:32009R1200

#### The LiveDate project on Nitrogen Excretion factors

The key indicator 'Gross Nutrient Balance' (GNB) is part of the set of agri-environmental indicators defined in the Commission Communication on the "Development of agri-environmental indicators for monitoring the integration of environmental concerns into the common agricultural policy"[^irena]. The Eurostat/OECD Methodology and Handbook on Nutrient Budgets has been updated and amended in 2013[^eurostatnbudget]. Nitrogen excretion coefficients have been identified of a major source of uncertainty for the estimation of the GNB, with high relevance for other reporting obligations, including the nitrate directive, reporting of ammonia emissions under the CLRTAP and the NEC directive, as well (and importantly) for the quantification of N2O emissions from manure management and agricultural soils. An expert workshop was therefore organized on 28/03/2014 at Eurostat to discuss the possibility to improve the quality of N-excretion data by using a common improved methodology. A recommendation on such a common methodology served as the basis for discussion. The workshop was co-organized by JRC under the WG on Annual GHG inventories under the EU Climate Change Committee and was attended by agricultural experts of the EU GHG inventory system.

The following gives some information on the project that prepared the recommendations, as extracted from the report from Oenema et al. (2014)[^livedatereport].

> The general objective of the study "Nitrogen and phosphorus excretion coefficients for livestock;    Methodological studies in the field of Agro-Environmental Indicators; Lot1" (2012/S 87-142068)  is "to bring clarity into the issue of excretion coefficients so that a recommendation on a single, common methodology to calculate N and P excretion coefficients can be identified". The recommendation for a uniform and standard methodology for estimating N and P excretion coefficients must be based on a thorough analysis of the strength and weaknesses of the existing methodologies and on the data availability and quality in the Member States. 

> The specific objectives of the study were:

> * To create an overview of the different methodologies used in Europe to calculate excretion factors for N and P, and analyse their strengths and weaknesses;
> *	To set up a database with the excretion factors presently used in different reporting systems and describe the main factors that cause distortion within a country and across the EU;
> *	To provide guidelines for a coherent methodology, consistent with IPCC and CLTRP guidelines, for calculating N and P excretion factors, and taking into consideration the animal balance and taking into account different methodologies identifies under the first bullet point;
> *	To create default P-excretion factors that can be used by the countries who do not have yet own factors calculated;

The recommendations of the LiveDate project from the authors of the report were:

> *	It is recommended to use the mass balance as a common and universally applicable method to estimate N and P excretion coefficients per animal category across EU-28: 

> * * N~excretion~ = N~intake~ - N~retention~

> * * P~excretion~ = P~intake~ - P~retention~

> *    We recommend that the European Commission encourages Member States to invest in Tier 2 and 3 methods for key animal categories (and hence in country-specific, region-specific and/or year-specific excretion coefficients). 

> *    We recommend that the European Commission encourages Member States to use a 3-Tier approach for the collection of data and information needed to estimate N and P excretion coefficients, so as to address differences between countries in livestock production and data collecting/processing infrastructure, and to economize on data collection/processing efforts. The three Tiers differ in the origin, scale and frequency of data and information collection.  

> *    We recommend that the European Commission encourages Member States to use a Tier 3 approach for all key animal categories when livestock density in a country is > 2 livestock units per ha (>2 LSU per ha), equivalent to an excretion of about > 200 kg N or the inter-annual variation in N excretion by key animal categories is relatively large due to the effects of changing weather conditions and market prices.
> *    We recommend that the European Commission encourages Member States to use a Tier 2 approach for all main animal categories when livestock density in a country is between 0.5 and 2 LSU per ha (equivalent to an excretion of between about 50 and 200 kg N, under the condition that the inter-annual variation in N excretion by key animal categories is relatively small.

> *    We recommend that the European Commission reviews the current default N and P excretion coefficients of all animal categories and decides on a list of N and P excretion coefficients. Member States are recommended to use this list as a Tier 1 approach for all animal categories within a country when livestock density is <0.5 livestock units per ha (<0.5 LSU per ha, also at regional levels), which is equivalent to about 50 kg N and 10 kg P per ha agricultural land per year. 

> *    We recommend that the European Commission encourages Member States to use region-specific N and P excretion coefficients when N and P excretion coefficients of the main animal categories differ significantly (>20%) between regions.

> *    We recommend that the European Commission makes computer programs available to Member States to encourage the calculation of the N and P excretion per animal category at regional and national levels in a uniform way. It is also recommended to provide training courses for the use of these programs and the calculation of the N and P excretion coefficients. 

> *    We recommend that the European Commission encourages Member States to have well-documented and accessible methods for the estimation of N and P excretion coefficients per animal category. These reports should be updated once every 3-5 years and reviewed by external experts.

> *    We recommend that the European Commission encourages Member States to harmonise the various animal categories in formal policy reporting. We recommend that the FSS categorization is taken as the main list of animal categories for policy reporting, also because the inventory of the number of animals takes place regularly according to the FSS list of animal categories. We recommend also that a transparent scheme and computer program is developed for translating the inventory data of FSS into the animal categories of secondary databases (e.g., UNFCCC/IPCC-2006, EMEP/EEA, Nitrates Directive, FAO and OECD). The development of a uniform nomenclature for animal categories would be useful too, which should include definitions about key, main, minor, primary, secondary, functional categories 

> *    We recommend that the European Commission encourages Member States to conduct a secondary animal categorization for key animal categories (e.g., cattle, pigs and poultry), when more than 20% of the animals are in another system and when the N and/or P excretion coefficients differ by more than 20% from the overall mean N and P excretion coefficients. We recommend that the following aspects are considered for distinguishing different production systems:
> * * Fast-growing and heavy breeds vs slow-growing breeds
> * * Organic production systems vs common production systems
> * * Housed ruminants vs grazing ruminants
> * * Caged poultry vs free-range poultry
> * Equally important is that the excretion coefficients can be translated in a transparent and well-documented manner from such secondary categories to the main categories of the FSS.

> * We recommend that the European Commission conducts a review of the diversity of production systems and feeding practices within a country for the main animal categories cattle, pigs and poultry once in 5 yrs, so as to trace changes in production systems, including organic versus conventional systems, housed vs grazing ruminants, caged versus free range poultry, and fast growing breeds versus slow growing breeds. 

> * We recommend that the European Commission encourages Member States to review and update the N and P retention coefficients for all animal categories once in 5-10 yrs. All data should be stored in a database accessible by all Member States.

> * We recommend that the European Commission conducts a review and adjusts/modifies/updates the classification system of livestock units (as presented also in Table 5 of this report), and livestock density, so as to better reflect the diversity of animals within an category and more in general the impact of livestock on the environment. 


[^irena]: &#09;http://epp.eurostat.ec.europa.eu/portal/page/portal/agri_environmental_indicators/introduction
[^eurostatnbudget]: &#09;http://epp.eurostat.ec.europa.eu/portal/page/portal/agri_environmental_indicators/documents/Nutrient_Budgets_Handbook_%28CPSA_AE_109%29_corrected3.pdf
[^livedatereport]: &#09;Oenema, O., Sebek, L., Kros, H., Lesschen, J.P., van Krimpen, M., Bikker, P., van Vuuren, A., Velthof, G., 2014. Guidelines for a common methodology to estimate nitrogen and phosphorus excretion coefficients per animal category in eu-28. final report to eurostat, in: Eurostat (Ed.), Methodological studies in the field of Agro-Environmental Indictors. Eurostat, Luxembourg, pp. 1?108.


#### Regionalisation of the Gross Nutrient Budget with the CAPRI model 

The JRC was cooperating with EUROSTAT on a methodology to use the CAPRI model[^capriweb] for the regionalisation of the Gross Nutrient Budget (GNB) indicators (nitrogen and phosphorus) that needs to be reported regularly by countries to EUROSTAT and OECD. The GNBs are identified as one of the key agro-environmental indicators. Current reporting occurs at the national level. For policy making, a higher resolution, matching with legislative and environmental boundaries (NVZ, watershed) rather than administrative boundaries (country) is required. The CAPRI model is an economic model for agriculture, which has an environmental accounting model integrated. It has a spatial resolution of NUTS2 and reports, a.o. Nitrogen Balances at this level. The CAPRI model has a down-scaling module integrated which estimates land use shares and environmental indicators at the pixel level (1 km by 1 km). The use of the CAPRI model is motivated in view of the lack of methodology for regionalisation of the GNB and the high costs associated with building up such systems in the countries at one hand, and the thrive to harmonise the conceptual approaches. 

[^capriweb]: &#09;http://www.capri-model.org/

The Working Group (WG) on agri-environmental indicators (AEI, February 2012) and the subsequent Standing Committee for Agricultural Statistics (CPSA, May 2012) decided to start a pilot projects on regionalising Gross Nitrogen Balance (GNB) with the CAPRI model. The objective of the pilot project is to evaluate differences between national GNB and the GNB calculated with CAPRI at the country and the NUTS2 scale. Italy, France, Germany and Hungary volunteered for this pilot project. The RegNiBal project (Regionalisation of Nitrogen Balances with the CAPRI Model - Pilot Project) started in February 2013. The overall goal was to use the CAPRI model to provide (operationally) regional GNB data to complement the national Eurostat/OECD GNBs.

Four countries volunteered to share their national GNB estimates with the CAPRI team which were analyzed on differences with CAPRI estimates and recommendations were formulated to improve both national methods and the CAPRI model:

* France
* Germany
* Italy
* Hungary

The conclusions formulated in the final RegNiBal report[^regnibal] included:

> A total of 31 'issues' were identified that were related to major discrepancies between the methods and warranted further assessment. At the end of the project, 12 of the identified issues were solved, one was partially solved and 18 could not be solved, but some progress was achieved and concrete recommendations were made for almost all of them. The results and achievements of RegNiBal are summarised in Annex 12.

> At the start of the RegNiBal project CAPRI data was generally judged to be more reliable than national data. The situation has changed with the improvements described above; at present, further analysis is needed to see whether CAPRI or national data is ?better? with regard to the remaining unresolved issues.

> Overall, N excretion by swine and N removal by grass are considered the most important unresolved issues because of their considerable impact on N-input and N-output. The animal budget analysis for swine of DE and FR shows that CAPRI estimates higher feed intake than the national methodologies. Countries are not always sufficiently accurate in estimating and/or using the average number of animals and N-excretion coefficients in N manure excretion estimations. For the estimates of dry matter yields of grassland, the differentiation of permanent grassland according to the proposal of the GRASSDATE project (Velthof et al 2014)[^velthof2014] would likely help (grassland out of production but maintained, unimproved grassland (including both sole use and  common land) and improved grassland (by N-input levels <50, 50-100, >100 kg N/ha/yr, sole use and common land). 

[^velthof2014]: &#09;Velthof, G.L., Lesschen, J.P., Schils, R.L.M., Smit, A., Elbersen, B.S., Hazeu, G.W., Mucher, C.A., Oenema, O., 2014. Grassland areas , production and use. Lot 2. Methodological studies in the field of Agro-Environmental Indicators. Alterra Wageningen UR, Wageningen, The Netherlands.

> The CAPRI model is very strong in several parts of GNB calculations, and the RegNiBal project enabled us to identify several possible improvements in national data and methods. The use of the animal budget to estimate N excretion is a major asset in the CAPRI methodology, but runs the risk of outliers if the use of feed in the statistical sources is overestimated. There is large uncertainty in grass yield and other (non-marketable) fodder yield and their N content. This affects the accuracy of national data as well. The other major areas of difficulties for the CAPRI model are the following: (i) Seed and planting materials should be explicit in the CAPRI GNB; (ii) N from organic fertilisers (other than manure) and manure withdrawal, stocks, and import estimations are not considered in the CAPRI model.

> The CAPRI model can be used to calculate both land N budgets (GNB) and farm N budgets. The possibility of comparing the GNB with the farm N-budget helps to constrain the N-surplus results. For the farm N-budget, feed and fodder produced in the country (or region) and manure excreted and applied within the country (or region) are considered as internal flows and thus do not need to be estimated to quantify the N-surplus; data on imported feed and exported animal products are needed instead (for details on the comparison of the two approaches, see Leip et al 2011[^leip2011nbudgets]). In the CAPRI model, data on animal products and imported feeds are available from statistical sources and are thus more reliable than the data on the N intake of fodder and manure excretion, which would not be required. 
> Generally, the RegNiBal project showed that the CAPRI model could be adequate to provide national (and later regional and spatially explicit) GNBs. However, for the four countries assessed, additional work needs to be carried out to understand residual disagreements in the data.

[^regnibal]: &#09;&#214;zbek, F.S., Leip, A., Weiss, F., Grassart, L., Hofmeier, M., Kukucka, M., Pallotti, A., Patay, A., Thuen, T., 2015. Regionalisation of Nitrogen Balances with the CAPRI Model ( RegNiBal ) Pilot project in support of the Eurostat Working Group on Agri-Environmental Indicators. Publications Office of the European Union, Luxembourg. doi: http://dx.doi.org/10.2788/078406.

[^leip2011nbudgets]: &#09;Leip, A., Britz, W., Weiss, F., de Vries, W., 2011. Farm, land, and soil nitrogen budgets for agriculture in Europe calculated with CAPRI. Environ. Pollut. 159, 3243?53. doi: http://dx.doi.org/10.1016/j.envpol.2011.01.040.


#### Workshop on improving national inventories for agriculture (2014)

Under the WG1 on Annual GHG inventories under the EU Climate Change Committee a workshop on improving GHG inventories in the sector agriculture was organized by the Joint Research Centre as part of the 7^th^ Non-CO2 Greenhouse Gas Conference (NCGG7), held November 5-7, 2014 Amsterdam, the Netherlands[^ncggweb]. The workshop was co-organized by CEH in support of the UK greenhouse gas inventory programme. 

[^ncggweb]: &#09;http://www.ncgg.info/ 

The session raised a high interest, contained high quality presentations and allowed scientists, IPCC and FAO representatives and country delegates to discuss about greenhouse accounting methods, their difficulties and challenges to use IPCC guidelines, to select the appropriate tier methods and to design country-specific methodologies which allow reducing uncertainties. From a total attendance of about 200 conference participants and five parallel sessions, this session was temporary attended by almost 100 scientists.

The workshop focused on N2O emissions from agricultural soils, as they are highly uncertain yet are often estimated with default methodology in lack of country-specific data of sufficient quality. N2O emissions from agricultural soils are dominating the uncertainty of the total GHG emissions for many countries. The programme included presentations covering the whole range of aspects of N2O emission estimates: the availability of flux data in Europe and network design strategies (Rene Dechow, Thuenen Institute, DE),  use of process-based models in GHG inventories (Steve del Grosso, USDA) to inverse methods to estimated national total N2O emissions (Rona Thompson, NILU, NO). Further presentation gave national examples on GHG improvements, such as UK (general), NZ (pasture emissions), Thailand (emissions from rice), Norway (emissions from dairy farms) and on the link to IPCC guidelines and the IPCC Emission Factor Database (Kiyoto Tanabe (see below) and Baasansuren Jamsranjav, IPCC TFI TSU). A broader picture was given on the basis of the FAOSTAT GHG Database (FrancescoTubiello) and the CAPRI model (Carmona and Leip: The calculation of greenhouse gas emissions in the European agricultural sector; how much does the method matter?). Introduction and expectations were formulated by a presentation from Velina Pendolovska (DG Climate Action).

A final brainstorming exercise was done about how modelling and measurements could be improved in a way to reduce uncertainties, improve accuracy of measures and optimise resources. There was a debate around whether new models are needed or focusing on reducing the uncertainty in current models would be preferable, for example using the results of inverse modelling to contrast results. There is an agreement on the acceptability of simple models or inverse models for emission accounting at high scales, while more complex process-based models are needed when designing mitigation options. The problem of nitrogen surplus was pointed out as a proxy of N2O emissions, which also informs about other additional pollution problems. About the estimation of uncertainties, the group agreed on the need, first of all, to improve their estimation. It seemed a general impression that uncertainties are usually overestimated, but it is difficult to quantify objectively. Another point that needs attention is the activity data: statistics do not always match at national level, and sometimes models demand a high quantity of data which is not available. Getting better activity data is important prior to focus on emission estimations.

As a conclusion, the combination of an expert meeting in support of the EU GHG inventory system and an international scientific conference was very successful, as it provided a high density of expertise that country delegates could use. The NCGG conference series is ideal for this purpose.


